#ifndef NOVA_ORIGIN_INFERENCE_TAGS_H
#define NOVA_ORIGIN_INFERENCE_TAGS_H

/* ConstraintKind definition */
#define NOVA_ORIGIN_INFERENCE_CONSTRAINTKIND_OUTLIVES 0
#define NOVA_ORIGIN_INFERENCE_CONSTRAINTKIND_PATHHASORIGIN 1
#define NOVA_ORIGIN_INFERENCE_CONSTRAINTKIND_CALLPROPAGATE 2

#endif

