#ifndef NOVA_PATH_ANALYSIS_TAGS_H
#define NOVA_PATH_ANALYSIS_TAGS_H

/* ConditionKind definition */
#define NOVA_PATH_ANALYSIS_CONDITIONKIND_ISTRUE 0
#define NOVA_PATH_ANALYSIS_CONDITIONKIND_ISFALSE 1
#define NOVA_PATH_ANALYSIS_CONDITIONKIND_EQUALS 2
#define NOVA_PATH_ANALYSIS_CONDITIONKIND_NOTEQUALS 3
#define NOVA_PATH_ANALYSIS_CONDITIONKIND_ISSOME 4
#define NOVA_PATH_ANALYSIS_CONDITIONKIND_ISNONE 5

/* PredicateKind definition */
#define NOVA_PATH_ANALYSIS_PREDICATEKIND_NONNULL 6
#define NOVA_PATH_ANALYSIS_PREDICATEKIND_INITIALIZED 7
#define NOVA_PATH_ANALYSIS_PREDICATEKIND_MOVED 8
#define NOVA_PATH_ANALYSIS_PREDICATEKIND_BORROWED 9

#endif

