#ifndef NOVA_CANONICAL_IR_TAGS_H
#define NOVA_CANONICAL_IR_TAGS_H

/* CoreIR definition */
#define NOVA_CANONICAL_IR_COREIR_FUNC 0
#define NOVA_CANONICAL_IR_COREIR_WHEN 1
#define NOVA_CANONICAL_IR_COREIR_LOOP 2
#define NOVA_CANONICAL_IR_COREIR_GIVE 3
#define NOVA_CANONICAL_IR_COREIR_BINOP 4
#define NOVA_CANONICAL_IR_COREIR_UNOP 5
#define NOVA_CANONICAL_IR_COREIR_CALL 6
#define NOVA_CANONICAL_IR_COREIR_LOAD 7
#define NOVA_CANONICAL_IR_COREIR_STORE 8
#define NOVA_CANONICAL_IR_COREIR_LITERAL 9
#define NOVA_CANONICAL_IR_COREIR_ALLOC 10
#define NOVA_CANONICAL_IR_COREIR_COMPUTEBLOCK 11

/* IRType definition */
#define NOVA_CANONICAL_IR_IRTYPE_VOID 12
#define NOVA_CANONICAL_IR_IRTYPE_BOOL 13
#define NOVA_CANONICAL_IR_IRTYPE_I64 14
#define NOVA_CANONICAL_IR_IRTYPE_F64 15
#define NOVA_CANONICAL_IR_IRTYPE_STR 16
#define NOVA_CANONICAL_IR_IRTYPE_PTR 17
#define NOVA_CANONICAL_IR_IRTYPE_VEC 18
#define NOVA_CANONICAL_IR_IRTYPE_TENSOR 19
#define NOVA_CANONICAL_IR_IRTYPE_SHAPE 20

/* IRLit definition */
#define NOVA_CANONICAL_IR_IRLIT_BOOL 21
#define NOVA_CANONICAL_IR_IRLIT_I64 22
#define NOVA_CANONICAL_IR_IRLIT_F64 23
#define NOVA_CANONICAL_IR_IRLIT_STR 24

/* IROp definition */
#define NOVA_CANONICAL_IR_IROP_ADD 25
#define NOVA_CANONICAL_IR_IROP_SUB 26
#define NOVA_CANONICAL_IR_IROP_MUL 27
#define NOVA_CANONICAL_IR_IROP_DIV 28
#define NOVA_CANONICAL_IR_IROP_MOD 29
#define NOVA_CANONICAL_IR_IROP_EQ 30
#define NOVA_CANONICAL_IR_IROP_NE 31
#define NOVA_CANONICAL_IR_IROP_LT 32
#define NOVA_CANONICAL_IR_IROP_GT 33
#define NOVA_CANONICAL_IR_IROP_LE 34
#define NOVA_CANONICAL_IR_IROP_GE 35
#define NOVA_CANONICAL_IR_IROP_AND 36
#define NOVA_CANONICAL_IR_IROP_OR 37
#define NOVA_CANONICAL_IR_IROP_NOT 38
#define NOVA_CANONICAL_IR_IROP_BITAND 39
#define NOVA_CANONICAL_IR_IROP_BITOR 40
#define NOVA_CANONICAL_IR_IROP_BITXOR 41

#endif

