#ifndef NOVA_RUNTIME_EXTENSIONS_TAGS_H
#define NOVA_RUNTIME_EXTENSIONS_TAGS_H

/* LogLevel definition */
#define NOVA_RUNTIME_EXTENSIONS_LOGLEVEL_SILENT 0
#define NOVA_RUNTIME_EXTENSIONS_LOGLEVEL_ERROR 1
#define NOVA_RUNTIME_EXTENSIONS_LOGLEVEL_WARN 2
#define NOVA_RUNTIME_EXTENSIONS_LOGLEVEL_INFO 3
#define NOVA_RUNTIME_EXTENSIONS_LOGLEVEL_DEBUG 4
#define NOVA_RUNTIME_EXTENSIONS_LOGLEVEL_TRACE 5

#endif

