#ifndef NOVA_CROSS_COMPILER_TAGS_H
#define NOVA_CROSS_COMPILER_TAGS_H

/* Target definition */
#define NOVA_CROSS_COMPILER_TARGET_X86_64_LINUX 0
#define NOVA_CROSS_COMPILER_TARGET_X86_64_WINDOWS 1
#define NOVA_CROSS_COMPILER_TARGET_X86_64_MACOS 2
#define NOVA_CROSS_COMPILER_TARGET_ARM64_LINUX 3
#define NOVA_CROSS_COMPILER_TARGET_ARM64_MACOS 4
#define NOVA_CROSS_COMPILER_TARGET_WASM32 5
#define NOVA_CROSS_COMPILER_TARGET_RISCV64 6

#endif

