#ifndef NOVA_SIMD_TAGS_H
#define NOVA_SIMD_TAGS_H

/* SIMDISASet definition */
#define NOVA_SIMD_SIMDISASET_SSE4_2 0
#define NOVA_SIMD_SIMDISASET_AVX 1
#define NOVA_SIMD_SIMDISASET_AVX2 2
#define NOVA_SIMD_SIMDISASET_AVX512 3
#define NOVA_SIMD_SIMDISASET_NEON 4
#define NOVA_SIMD_SIMDISASET_SVE 5

#endif

