#ifndef NOVA_PLATFORM_MENUS_TAGS_H
#define NOVA_PLATFORM_MENUS_TAGS_H

/* MenuItemType definition */
#define NOVA_PLATFORM_MENUS_MENUITEMTYPE_NORMAL 0
#define NOVA_PLATFORM_MENUS_MENUITEMTYPE_SEPARATOR 1
#define NOVA_PLATFORM_MENUS_MENUITEMTYPE_CHECKBOX 2
#define NOVA_PLATFORM_MENUS_MENUITEMTYPE_RADIO 3
#define NOVA_PLATFORM_MENUS_MENUITEMTYPE_SUBMENU 4

/* MenuError definition */
#define NOVA_PLATFORM_MENUS_MENUERROR_CREATIONFAILED 5
#define NOVA_PLATFORM_MENUS_MENUERROR_INVALIDCONFIG 6
#define NOVA_PLATFORM_MENUS_MENUERROR_PLATFORMERROR 7

#endif

