#ifndef NOVA_SYMBOL_TABLE_TAGS_H
#define NOVA_SYMBOL_TABLE_TAGS_H

/* Visibility definition */
#define NOVA_SYMBOL_TABLE_VISIBILITY_PRIVATE 0
#define NOVA_SYMBOL_TABLE_VISIBILITY_PUBLIC 1
#define NOVA_SYMBOL_TABLE_VISIBILITY_OPEN 2

/* ScopeKind definition */
#define NOVA_SYMBOL_TABLE_SCOPEKIND_GLOBAL 3
#define NOVA_SYMBOL_TABLE_SCOPEKIND_MODULE 4
#define NOVA_SYMBOL_TABLE_SCOPEKIND_FUNCTION 5
#define NOVA_SYMBOL_TABLE_SCOPEKIND_BLOCK 6
#define NOVA_SYMBOL_TABLE_SCOPEKIND_LOOP 7
#define NOVA_SYMBOL_TABLE_SCOPEKIND_MATCHARM 8

#endif

