#ifndef NOVA_MLIR_INTEGRATION_TAGS_H
#define NOVA_MLIR_INTEGRATION_TAGS_H

/* MLIRDialect definition */
#define NOVA_MLIR_INTEGRATION_MLIRDIALECT_ARITH 0
#define NOVA_MLIR_INTEGRATION_MLIRDIALECT_SCF 1
#define NOVA_MLIR_INTEGRATION_MLIRDIALECT_FUNC 2
#define NOVA_MLIR_INTEGRATION_MLIRDIALECT_LINALG 3
#define NOVA_MLIR_INTEGRATION_MLIRDIALECT_VECTOR 4
#define NOVA_MLIR_INTEGRATION_MLIRDIALECT_GPU 5
#define NOVA_MLIR_INTEGRATION_MLIRDIALECT_NOVA 6

#endif

