#ifndef NOVA_VALUES_TAGS_H
#define NOVA_VALUES_TAGS_H

/* Value definition */
#define NOVA_VALUES_VALUE_REGISTER 0
#define NOVA_VALUES_VALUE_CONST 1
#define NOVA_VALUES_VALUE_ARGUMENT 2
#define NOVA_VALUES_VALUE_GLOBAL 3
#define NOVA_VALUES_VALUE_UNDEF 4

/* Constant definition */
#define NOVA_VALUES_CONSTANT_INT 5
#define NOVA_VALUES_CONSTANT_UINT 6
#define NOVA_VALUES_CONSTANT_FLOAT 7
#define NOVA_VALUES_CONSTANT_BOOL 8
#define NOVA_VALUES_CONSTANT_NULL 9
#define NOVA_VALUES_CONSTANT_STRING 10
#define NOVA_VALUES_CONSTANT_ARRAY 11
#define NOVA_VALUES_CONSTANT_STRUCT 12
#define NOVA_VALUES_CONSTANT_ZEROINITIALIZER 13

#endif

