#ifndef NOVA_CONSTRAINT_TAGS_H
#define NOVA_CONSTRAINT_TAGS_H

/* Effect definition */
#define NOVA_CONSTRAINT_EFFECT_PURE 0
#define NOVA_CONSTRAINT_EFFECT_IO 1
#define NOVA_CONSTRAINT_EFFECT_DIVERGE 2
#define NOVA_CONSTRAINT_EFFECT_PANIC 3
#define NOVA_CONSTRAINT_EFFECT_ASYNC 4
#define NOVA_CONSTRAINT_EFFECT_CUSTOM 5
#define NOVA_CONSTRAINT_EFFECT_VAR 6
#define NOVA_CONSTRAINT_EFFECT_UNION 7

/* EffectConstraint definition */
#define NOVA_CONSTRAINT_EFFECTCONSTRAINT_EQ 8
#define NOVA_CONSTRAINT_EFFECTCONSTRAINT_SUB 9
#define NOVA_CONSTRAINT_EFFECTCONSTRAINT_BOUND 10

#endif

