#ifndef NOVA_CONTEXT_TAGS_H
#define NOVA_CONTEXT_TAGS_H

/* ThermalState definition */
#define NOVA_CONTEXT_THERMALSTATE_COOL 0
#define NOVA_CONTEXT_THERMALSTATE_WARM 1
#define NOVA_CONTEXT_THERMALSTATE_HOT 2
#define NOVA_CONTEXT_THERMALSTATE_CRITICAL 3

/* Platform definition */
#define NOVA_CONTEXT_PLATFORM_IOS 4
#define NOVA_CONTEXT_PLATFORM_ANDROID 5
#define NOVA_CONTEXT_PLATFORM_DESKTOP 6
#define NOVA_CONTEXT_PLATFORM_SERVER 7

#endif

