#ifndef NOVA_NATIVE_WIDGETS_TAGS_H
#define NOVA_NATIVE_WIDGETS_TAGS_H

/* TextAlignment definition */
#define NOVA_NATIVE_WIDGETS_TEXTALIGNMENT_LEFT 0
#define NOVA_NATIVE_WIDGETS_TEXTALIGNMENT_CENTER 1
#define NOVA_NATIVE_WIDGETS_TEXTALIGNMENT_RIGHT 2

/* LayoutType definition */
#define NOVA_NATIVE_WIDGETS_LAYOUTTYPE_ABSOLUTE 3
#define NOVA_NATIVE_WIDGETS_LAYOUTTYPE_VERTICAL 4
#define NOVA_NATIVE_WIDGETS_LAYOUTTYPE_HORIZONTAL 5
#define NOVA_NATIVE_WIDGETS_LAYOUTTYPE_GRID 6

/* FontWeight definition */
#define NOVA_NATIVE_WIDGETS_FONTWEIGHT_THIN 7
#define NOVA_NATIVE_WIDGETS_FONTWEIGHT_LIGHT 8
#define NOVA_NATIVE_WIDGETS_FONTWEIGHT_REGULAR 9
#define NOVA_NATIVE_WIDGETS_FONTWEIGHT_MEDIUM 10
#define NOVA_NATIVE_WIDGETS_FONTWEIGHT_BOLD 11
#define NOVA_NATIVE_WIDGETS_FONTWEIGHT_BLACK 12

/* FontStyle definition */
#define NOVA_NATIVE_WIDGETS_FONTSTYLE_NORMAL 13
#define NOVA_NATIVE_WIDGETS_FONTSTYLE_ITALIC 14
#define NOVA_NATIVE_WIDGETS_FONTSTYLE_OBLIQUE 15

/* WidgetError definition */
#define NOVA_NATIVE_WIDGETS_WIDGETERROR_CREATIONFAILED 16
#define NOVA_NATIVE_WIDGETS_WIDGETERROR_INVALIDCONFIG 17
#define NOVA_NATIVE_WIDGETS_WIDGETERROR_PLATFORMERROR 18

#endif

