#ifndef NOVA_UNIFIED_UI_TAGS_H
#define NOVA_UNIFIED_UI_TAGS_H

/* Element definition */
#define NOVA_UNIFIED_UI_ELEMENT_NONE 0
#define NOVA_UNIFIED_UI_ELEMENT_TEXT 1
#define NOVA_UNIFIED_UI_ELEMENT_NODE 2
#define NOVA_UNIFIED_UI_ELEMENT_COMPONENT 3
#define NOVA_UNIFIED_UI_ELEMENT_FRAGMENT 4
#define NOVA_UNIFIED_UI_ELEMENT_PORTAL 5

/* AttrValue definition */
#define NOVA_UNIFIED_UI_ATTRVALUE_TEXT 6
#define NOVA_UNIFIED_UI_ATTRVALUE_NUMBER 7
#define NOVA_UNIFIED_UI_ATTRVALUE_BOOL 8
#define NOVA_UNIFIED_UI_ATTRVALUE_HANDLER 9
#define NOVA_UNIFIED_UI_ATTRVALUE_STYLE 10
#define NOVA_UNIFIED_UI_ATTRVALUE_NONE 11

/* PropValue definition */
#define NOVA_UNIFIED_UI_PROPVALUE_STR 12
#define NOVA_UNIFIED_UI_PROPVALUE_INT 13
#define NOVA_UNIFIED_UI_PROPVALUE_FLOAT 14
#define NOVA_UNIFIED_UI_PROPVALUE_BOOL 15
#define NOVA_UNIFIED_UI_PROPVALUE_LIST 16
#define NOVA_UNIFIED_UI_PROPVALUE_ELEMENT 17
#define NOVA_UNIFIED_UI_PROPVALUE_NONE 18

/* PlatformEvent definition */
#define NOVA_UNIFIED_UI_PLATFORMEVENT_CLICK 19
#define NOVA_UNIFIED_UI_PLATFORMEVENT_DBLCLICK 20
#define NOVA_UNIFIED_UI_PLATFORMEVENT_INPUT 21
#define NOVA_UNIFIED_UI_PLATFORMEVENT_CHANGE 22
#define NOVA_UNIFIED_UI_PLATFORMEVENT_KEYDOWN 23
#define NOVA_UNIFIED_UI_PLATFORMEVENT_KEYUP 24
#define NOVA_UNIFIED_UI_PLATFORMEVENT_SCROLL 25
#define NOVA_UNIFIED_UI_PLATFORMEVENT_RESIZE 26
#define NOVA_UNIFIED_UI_PLATFORMEVENT_FOCUS 27
#define NOVA_UNIFIED_UI_PLATFORMEVENT_BLUR 28
#define NOVA_UNIFIED_UI_PLATFORMEVENT_TOUCH 29
#define NOVA_UNIFIED_UI_PLATFORMEVENT_CUSTOM 30

/* TouchPhase definition */
#define NOVA_UNIFIED_UI_TOUCHPHASE_BEGAN 31
#define NOVA_UNIFIED_UI_TOUCHPHASE_MOVED 32
#define NOVA_UNIFIED_UI_TOUCHPHASE_ENDED 33
#define NOVA_UNIFIED_UI_TOUCHPHASE_CANCELLED 34

/* Mutation definition */
#define NOVA_UNIFIED_UI_MUTATION_CREATEELEMENT 35
#define NOVA_UNIFIED_UI_MUTATION_CREATETEXTNODE 36
#define NOVA_UNIFIED_UI_MUTATION_SETATTRIBUTE 37
#define NOVA_UNIFIED_UI_MUTATION_REMOVEATTRIBUTE 38
#define NOVA_UNIFIED_UI_MUTATION_APPENDCHILD 39
#define NOVA_UNIFIED_UI_MUTATION_INSERTBEFORE 40
#define NOVA_UNIFIED_UI_MUTATION_REMOVENODE 41
#define NOVA_UNIFIED_UI_MUTATION_MOVENODE 42
#define NOVA_UNIFIED_UI_MUTATION_UPDATETEXT 43
#define NOVA_UNIFIED_UI_MUTATION_ADDEVENTLISTENER 44
#define NOVA_UNIFIED_UI_MUTATION_REMOVEEVENTLISTENER 45
#define NOVA_UNIFIED_UI_MUTATION_SETSTYLE 46
#define NOVA_UNIFIED_UI_MUTATION_FOCUS 47
#define NOVA_UNIFIED_UI_MUTATION_SCROLLTO 48

/* RenderTarget definition */
#define NOVA_UNIFIED_UI_RENDERTARGET_DESKTOP 49
#define NOVA_UNIFIED_UI_RENDERTARGET_WEB 50
#define NOVA_UNIFIED_UI_RENDERTARGET_IOS 51
#define NOVA_UNIFIED_UI_RENDERTARGET_ANDROID 52
#define NOVA_UNIFIED_UI_RENDERTARGET_TERMINAL 53

/* AppTheme definition */
#define NOVA_UNIFIED_UI_APPTHEME_LIGHT 54
#define NOVA_UNIFIED_UI_APPTHEME_DARK 55
#define NOVA_UNIFIED_UI_APPTHEME_SYSTEM 56
#define NOVA_UNIFIED_UI_APPTHEME_CUSTOM 57

/* Route definition */
#define NOVA_UNIFIED_UI_ROUTE_HOME 58
#define NOVA_UNIFIED_UI_ROUTE_ABOUT 59
#define NOVA_UNIFIED_UI_ROUTE_SETTINGS 60
#define NOVA_UNIFIED_UI_ROUTE_DYNAMIC 61
#define NOVA_UNIFIED_UI_ROUTE_NOTFOUND 62

#endif

