#ifndef NOVA_IO_TAGS_H
#define NOVA_IO_TAGS_H

/* Error definition */
#define NOVA_IO_ERROR_NOTFOUND 0
#define NOVA_IO_ERROR_PERMISSIONDENIED 1
#define NOVA_IO_ERROR_CONNECTIONREFUSED 2
#define NOVA_IO_ERROR_CONNECTIONRESET 3
#define NOVA_IO_ERROR_CONNECTIONABORTED 4
#define NOVA_IO_ERROR_NOTCONNECTED 5
#define NOVA_IO_ERROR_ADDRINUSE 6
#define NOVA_IO_ERROR_ADDRNOTAVAILABLE 7
#define NOVA_IO_ERROR_BROKENPIPE 8
#define NOVA_IO_ERROR_ALREADYEXISTS 9
#define NOVA_IO_ERROR_WOULDBLOCK 10
#define NOVA_IO_ERROR_INVALIDINPUT 11
#define NOVA_IO_ERROR_INVALIDDATA 12
#define NOVA_IO_ERROR_TIMEDOUT 13
#define NOVA_IO_ERROR_WRITEZERO 14
#define NOVA_IO_ERROR_INTERRUPTED 15
#define NOVA_IO_ERROR_OTHER 16

#endif

