#ifndef NOVA_SSR_SUPPORT_TAGS_H
#define NOVA_SSR_SUPPORT_TAGS_H

/* HydrationResult definition */
#define NOVA_SSR_SUPPORT_HYDRATIONRESULT_SUCCESS 0
#define NOVA_SSR_SUPPORT_HYDRATIONRESULT_FAILED 1
#define NOVA_SSR_SUPPORT_HYDRATIONRESULT_SKIPPED 2
#define NOVA_SSR_SUPPORT_HYDRATIONRESULT_TIMEOUT 3

/* StreamChunk definition */
#define NOVA_SSR_SUPPORT_STREAMCHUNK_HTML 4
#define NOVA_SSR_SUPPORT_STREAMCHUNK_COMPONENTDATA 5
#define NOVA_SSR_SUPPORT_STREAMCHUNK_SCRIPT 6
#define NOVA_SSR_SUPPORT_STREAMCHUNK_STYLE 7
#define NOVA_SSR_SUPPORT_STREAMCHUNK_END 8

/* MiddlewareError definition */
#define NOVA_SSR_SUPPORT_MIDDLEWAREERROR_REQUESTPROCESSINGFAILED 9
#define NOVA_SSR_SUPPORT_MIDDLEWAREERROR_RESPONSEPROCESSINGFAILED 10

/* SSRError definition */
#define NOVA_SSR_SUPPORT_SSRERROR_COMPONENTRENDERFAILED 11
#define NOVA_SSR_SUPPORT_SSRERROR_HYDRATIONFAILED 12
#define NOVA_SSR_SUPPORT_SSRERROR_ROUTINGERROR 13
#define NOVA_SSR_SUPPORT_SSRERROR_TEMPLATEERROR 14

#endif

