#ifndef NOVA_DEVICE_APIS_TAGS_H
#define NOVA_DEVICE_APIS_TAGS_H

/* SensorType definition */
#define NOVA_DEVICE_APIS_SENSORTYPE_ACCELEROMETER 0
#define NOVA_DEVICE_APIS_SENSORTYPE_GYROSCOPE 1
#define NOVA_DEVICE_APIS_SENSORTYPE_MAGNETOMETER 2
#define NOVA_DEVICE_APIS_SENSORTYPE_GPS 3
#define NOVA_DEVICE_APIS_SENSORTYPE_BAROMETER 4
#define NOVA_DEVICE_APIS_SENSORTYPE_PROXIMITY 5
#define NOVA_DEVICE_APIS_SENSORTYPE_AMBIENTLIGHT 6
#define NOVA_DEVICE_APIS_SENSORTYPE_THERMOMETER 7
#define NOVA_DEVICE_APIS_SENSORTYPE_HEARTRATE 8

/* SensorData definition */
#define NOVA_DEVICE_APIS_SENSORDATA_ACCELERATION 9
#define NOVA_DEVICE_APIS_SENSORDATA_ROTATION 10
#define NOVA_DEVICE_APIS_SENSORDATA_MAGNETICFIELD 11
#define NOVA_DEVICE_APIS_SENSORDATA_LOCATION 12
#define NOVA_DEVICE_APIS_SENSORDATA_PRESSURE 13
#define NOVA_DEVICE_APIS_SENSORDATA_PROXIMITY 14
#define NOVA_DEVICE_APIS_SENSORDATA_LIGHTLEVEL 15
#define NOVA_DEVICE_APIS_SENSORDATA_TEMPERATURE 16
#define NOVA_DEVICE_APIS_SENSORDATA_HEARTRATE 17

/* SensorError definition */
#define NOVA_DEVICE_APIS_SENSORERROR_NOTAVAILABLE 18
#define NOVA_DEVICE_APIS_SENSORERROR_PERMISSIONDENIED 19
#define NOVA_DEVICE_APIS_SENSORERROR_HARDWAREFAILURE 20
#define NOVA_DEVICE_APIS_SENSORERROR_TIMEOUT 21

/* CameraPosition definition */
#define NOVA_DEVICE_APIS_CAMERAPOSITION_FRONT 22
#define NOVA_DEVICE_APIS_CAMERAPOSITION_BACK 23

/* FlashMode definition */
#define NOVA_DEVICE_APIS_FLASHMODE_OFF 24
#define NOVA_DEVICE_APIS_FLASHMODE_ON 25
#define NOVA_DEVICE_APIS_FLASHMODE_AUTO 26

/* FocusMode definition */
#define NOVA_DEVICE_APIS_FOCUSMODE_AUTO 27
#define NOVA_DEVICE_APIS_FOCUSMODE_MANUAL 28
#define NOVA_DEVICE_APIS_FOCUSMODE_CONTINUOUS 29

/* CameraError definition */
#define NOVA_DEVICE_APIS_CAMERAERROR_NOTAVAILABLE 30
#define NOVA_DEVICE_APIS_CAMERAERROR_PERMISSIONDENIED 31
#define NOVA_DEVICE_APIS_CAMERAERROR_HARDWAREFAILURE 32
#define NOVA_DEVICE_APIS_CAMERAERROR_INVALIDCONFIGURATION 33

/* NotificationAction definition */
#define NOVA_DEVICE_APIS_NOTIFICATIONACTION_OPENED 34
#define NOVA_DEVICE_APIS_NOTIFICATIONACTION_DISMISSED 35
#define NOVA_DEVICE_APIS_NOTIFICATIONACTION_CUSTOM 36

/* NotificationError definition */
#define NOVA_DEVICE_APIS_NOTIFICATIONERROR_PERMISSIONDENIED 37
#define NOVA_DEVICE_APIS_NOTIFICATIONERROR_SCHEDULINGFAILED 38
#define NOVA_DEVICE_APIS_NOTIFICATIONERROR_NOTFOUND 39
#define NOVA_DEVICE_APIS_NOTIFICATIONERROR_SYSTEMERROR 40

/* StorageError definition */
#define NOVA_DEVICE_APIS_STORAGEERROR_FILENOTFOUND 41
#define NOVA_DEVICE_APIS_STORAGEERROR_DIRECTORYNOTFOUND 42
#define NOVA_DEVICE_APIS_STORAGEERROR_PERMISSIONDENIED 43
#define NOVA_DEVICE_APIS_STORAGEERROR_WRITEFAILED 44
#define NOVA_DEVICE_APIS_STORAGEERROR_READFAILED 45
#define NOVA_DEVICE_APIS_STORAGEERROR_CREATEFAILED 46
#define NOVA_DEVICE_APIS_STORAGEERROR_DELETEFAILED 47

/* ConnectionType definition */
#define NOVA_DEVICE_APIS_CONNECTIONTYPE_NONE 48
#define NOVA_DEVICE_APIS_CONNECTIONTYPE_WIFI 49
#define NOVA_DEVICE_APIS_CONNECTIONTYPE_CELLULAR 50
#define NOVA_DEVICE_APIS_CONNECTIONTYPE_ETHERNET 51
#define NOVA_DEVICE_APIS_CONNECTIONTYPE_UNKNOWN 52

/* HTTPMethod definition */
#define NOVA_DEVICE_APIS_HTTPMETHOD_GET 53
#define NOVA_DEVICE_APIS_HTTPMETHOD_POST 54
#define NOVA_DEVICE_APIS_HTTPMETHOD_PUT 55
#define NOVA_DEVICE_APIS_HTTPMETHOD_DELETE 56
#define NOVA_DEVICE_APIS_HTTPMETHOD_PATCH 57

/* NetworkError definition */
#define NOVA_DEVICE_APIS_NETWORKERROR_NOCONNECTION 58
#define NOVA_DEVICE_APIS_NETWORKERROR_TIMEOUT 59
#define NOVA_DEVICE_APIS_NETWORKERROR_INVALIDURL 60
#define NOVA_DEVICE_APIS_NETWORKERROR_SERVERERROR 61
#define NOVA_DEVICE_APIS_NETWORKERROR_UNKNOWN 62

#endif

