#ifndef NOVA_NOVA_INTERPRETER_TAGS_H
#define NOVA_NOVA_INTERPRETER_TAGS_H

/* Value definition */
#define NOVA_NOVA_INTERPRETER_VALUE_INTEGER 0
#define NOVA_NOVA_INTERPRETER_VALUE_FLOAT 1
#define NOVA_NOVA_INTERPRETER_VALUE_BOOLEAN 2
#define NOVA_NOVA_INTERPRETER_VALUE_STRING 3
#define NOVA_NOVA_INTERPRETER_VALUE_FUNCTION 4
#define NOVA_NOVA_INTERPRETER_VALUE_NULL 5

#endif

