#ifndef NOVA_ADVANCED_TAGS_H
#define NOVA_ADVANCED_TAGS_H

/* LogLevel definition */
#define NOVA_ADVANCED_LOGLEVEL_SILENT 0
#define NOVA_ADVANCED_LOGLEVEL_ERROR 1
#define NOVA_ADVANCED_LOGLEVEL_WARN 2
#define NOVA_ADVANCED_LOGLEVEL_INFO 3
#define NOVA_ADVANCED_LOGLEVEL_DEBUG 4
#define NOVA_ADVANCED_LOGLEVEL_TRACE 5

/* RuntimeState definition */
#define NOVA_ADVANCED_RUNTIMESTATE_INITIALIZING 6
#define NOVA_ADVANCED_RUNTIMESTATE_RUNNING 7
#define NOVA_ADVANCED_RUNTIMESTATE_SUSPENDED 8
#define NOVA_ADVANCED_RUNTIMESTATE_TERMINATING 9
#define NOVA_ADVANCED_RUNTIMESTATE_ERROR 10

/* RuntimeEvent definition */
#define NOVA_ADVANCED_RUNTIMEEVENT_SUSPEND 11
#define NOVA_ADVANCED_RUNTIMEEVENT_RESUME 12
#define NOVA_ADVANCED_RUNTIMEEVENT_TERMINATE 13
#define NOVA_ADVANCED_RUNTIMEEVENT_MEMORYWARNING 14
#define NOVA_ADVANCED_RUNTIMEEVENT_ACCESSIBILITYCHANGED 15
#define NOVA_ADVANCED_RUNTIMEEVENT_THEMECHANGED 16
#define NOVA_ADVANCED_RUNTIMEEVENT_ORIENTATIONCHANGED 17
#define NOVA_ADVANCED_RUNTIMEEVENT_NETWORKCHANGED 18
#define NOVA_ADVANCED_RUNTIMEEVENT_CUSTOM 19

/* Orientation definition */
#define NOVA_ADVANCED_ORIENTATION_PORTRAIT 20
#define NOVA_ADVANCED_ORIENTATION_LANDSCAPE 21
#define NOVA_ADVANCED_ORIENTATION_PORTRAITUPSIDEDOWN 22
#define NOVA_ADVANCED_ORIENTATION_LANDSCAPERIGHT 23

/* NetworkStatus definition */
#define NOVA_ADVANCED_NETWORKSTATUS_ONLINE 24
#define NOVA_ADVANCED_NETWORKSTATUS_OFFLINE 25
#define NOVA_ADVANCED_NETWORKSTATUS_CELLULAR 26
#define NOVA_ADVANCED_NETWORKSTATUS_WIFI 27

/* RuntimeError definition */
#define NOVA_ADVANCED_RUNTIMEERROR_INITFAILED 28
#define NOVA_ADVANCED_RUNTIMEERROR_GPUINITFAILED 29
#define NOVA_ADVANCED_RUNTIMEERROR_MLINITFAILED 30
#define NOVA_ADVANCED_RUNTIMEERROR_UIINITFAILED 31
#define NOVA_ADVANCED_RUNTIMEERROR_ACCESSIBILITYINITFAILED 32
#define NOVA_ADVANCED_RUNTIMEERROR_UNKNOWNERROR 33

#endif

