#ifndef NOVA_POSTGRES_TAGS_H
#define NOVA_POSTGRES_TAGS_H

/* PgValue definition */
#define NOVA_POSTGRES_PGVALUE_NULL 0
#define NOVA_POSTGRES_PGVALUE_BOOL 1
#define NOVA_POSTGRES_PGVALUE_INT 2
#define NOVA_POSTGRES_PGVALUE_FLOAT 3
#define NOVA_POSTGRES_PGVALUE_TEXT 4
#define NOVA_POSTGRES_PGVALUE_BYTES 5

#endif

