#ifndef NOVA_HTTP_TAGS_H
#define NOVA_HTTP_TAGS_H

/* Method definition */
#define NOVA_HTTP_METHOD_GET 0
#define NOVA_HTTP_METHOD_POST 1
#define NOVA_HTTP_METHOD_PUT 2
#define NOVA_HTTP_METHOD_DELETE 3
#define NOVA_HTTP_METHOD_PATCH 4
#define NOVA_HTTP_METHOD_HEAD 5
#define NOVA_HTTP_METHOD_OPTIONS 6

/* StatusCode definition */
#define NOVA_HTTP_STATUSCODE_OK = 200 7
#define NOVA_HTTP_STATUSCODE_CREATED = 201 8
#define NOVA_HTTP_STATUSCODE_NOCONTENT = 204 9
#define NOVA_HTTP_STATUSCODE_MOVEDPERMANENTLY = 301 10
#define NOVA_HTTP_STATUSCODE_FOUND = 302 11
#define NOVA_HTTP_STATUSCODE_BADREQUEST = 400 12
#define NOVA_HTTP_STATUSCODE_UNAUTHORIZED = 401 13
#define NOVA_HTTP_STATUSCODE_FORBIDDEN = 403 14
#define NOVA_HTTP_STATUSCODE_NOTFOUND = 404 15
#define NOVA_HTTP_STATUSCODE_INTERNALSERVERERROR = 500 16

#endif

