#ifndef NOVA_TYPES_TAGS_H
#define NOVA_TYPES_TAGS_H

/* IRType definition */
#define NOVA_TYPES_IRTYPE_VOID 0
#define NOVA_TYPES_IRTYPE_BOOL 1
#define NOVA_TYPES_IRTYPE_I8 2
#define NOVA_TYPES_IRTYPE_I16 3
#define NOVA_TYPES_IRTYPE_I32 4
#define NOVA_TYPES_IRTYPE_I64 5
#define NOVA_TYPES_IRTYPE_U8 6
#define NOVA_TYPES_IRTYPE_U16 7
#define NOVA_TYPES_IRTYPE_U32 8
#define NOVA_TYPES_IRTYPE_U64 9
#define NOVA_TYPES_IRTYPE_F16 10
#define NOVA_TYPES_IRTYPE_F32 11
#define NOVA_TYPES_IRTYPE_F64 12
#define NOVA_TYPES_IRTYPE_PTR 13
#define NOVA_TYPES_IRTYPE_ARRAY 14
#define NOVA_TYPES_IRTYPE_VECTOR 15
#define NOVA_TYPES_IRTYPE_STRUCT 16
#define NOVA_TYPES_IRTYPE_FUNCTION 17
#define NOVA_TYPES_IRTYPE_TENSOR 18
#define NOVA_TYPES_IRTYPE_NAMED 19

#endif

