#ifndef NOVA_AST_VISITOR_TAGS_H
#define NOVA_AST_VISITOR_TAGS_H

/* Expr definition */
#define NOVA_AST_VISITOR_EXPR_BLOCK 0
#define NOVA_AST_VISITOR_EXPR_IF 1
#define NOVA_AST_VISITOR_EXPR_MATCH 2
#define NOVA_AST_VISITOR_EXPR_WHILE 3
#define NOVA_AST_VISITOR_EXPR_FOR 4
#define NOVA_AST_VISITOR_EXPR_LET 5
#define NOVA_AST_VISITOR_EXPR_ASSIGN 6
#define NOVA_AST_VISITOR_EXPR_BORROW 7
#define NOVA_AST_VISITOR_EXPR_CALL 8
#define NOVA_AST_VISITOR_EXPR_FIELD 9
#define NOVA_AST_VISITOR_EXPR_INDEX 10
#define NOVA_AST_VISITOR_EXPR_VAR 11
#define NOVA_AST_VISITOR_EXPR_LITERAL 12

/* Stmt definition */
#define NOVA_AST_VISITOR_STMT_EXPR 13
#define NOVA_AST_VISITOR_STMT_LET 14
#define NOVA_AST_VISITOR_STMT_RETURN 15

/* Pattern definition */
#define NOVA_AST_VISITOR_PATTERN_WILDCARD 16
#define NOVA_AST_VISITOR_PATTERN_VAR 17
#define NOVA_AST_VISITOR_PATTERN_LITERAL 18

/* Literal definition */
#define NOVA_AST_VISITOR_LITERAL_INT 19
#define NOVA_AST_VISITOR_LITERAL_BOOL 20
#define NOVA_AST_VISITOR_LITERAL_STRING 21

/* Type definition */
#define NOVA_AST_VISITOR_TYPE_INT 22
#define NOVA_AST_VISITOR_TYPE_BOOL 23
#define NOVA_AST_VISITOR_TYPE_STRING 24
#define NOVA_AST_VISITOR_TYPE_UNIT 25

#endif

