#ifndef NOVA_H
#define NOVA_H

/*
 * Nova Execution Efficiency Layer
 * High-performance compute graph runtime in C11
 *
 * Priority order: Correctness → Determinism → Memory Efficiency → Performance
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* =========================================================================
 * Version
 * ========================================================================= */
#define NOVA_VERSION_MAJOR 1
#define NOVA_VERSION_MINOR 0
#define NOVA_VERSION_PATCH 0

/* =========================================================================
 * Limits
 * ========================================================================= */
#define NOVA_MAX_DIMS 8
#define NOVA_MAX_INPUTS 8
#define NOVA_MAX_OUTPUTS 8
#define NOVA_MAX_NODES 4096
#define NOVA_MAX_TENSORS 8192
#define NOVA_MAX_FUSED_OPS 16
#define NOVA_ARENA_ALIGNMENT 64 /* cache-line aligned */

/* =========================================================================
 * Error codes
 * ========================================================================= */
typedef enum {
  NOVA_OK = 0,
  NOVA_ERR_NULL_PTR = -1,
  NOVA_ERR_OOM = -2,
  NOVA_ERR_INVALID_GRAPH = -3,
  NOVA_ERR_CYCLE = -4,
  NOVA_ERR_BACKEND = -5,
  NOVA_ERR_SHAPE_MISMATCH = -6,
  NOVA_ERR_UNSUPPORTED = -7,
  NOVA_ERR_FULL = -8,
} NovaStatus;

/* =========================================================================
 * Data types
 * ========================================================================= */
typedef enum {
  NOVA_DTYPE_F32 = 0,
  NOVA_DTYPE_F16,
  NOVA_DTYPE_I32,
  NOVA_DTYPE_I8,
  NOVA_DTYPE_BOOL,
} NovaDType;

static inline size_t nova_dtype_size(NovaDType dt) {
  static const size_t sizes[] = {4, 2, 4, 1, 1};
  return sizes[(int)dt];
}

/* =========================================================================
 * Operation types
 * ========================================================================= */
typedef enum {
  NOVA_OP_NOP = 0,
  NOVA_OP_MATMUL,
  NOVA_OP_CONV2D,
  NOVA_OP_RELU,
  NOVA_OP_GELU,
  NOVA_OP_SIGMOID,
  NOVA_OP_SOFTMAX,
  NOVA_OP_LAYERNORM,
  NOVA_OP_BIAS_ADD,
  NOVA_OP_ADD,
  NOVA_OP_MUL,
  NOVA_OP_ATTENTION,
  NOVA_OP_RESHAPE,
  NOVA_OP_TRANSPOSE,
  NOVA_OP_COPY,
  /* Fused ops — generated by fusion engine */
  NOVA_OP_FUSED_MATMUL_BIAS_RELU,
  NOVA_OP_FUSED_MATMUL_BIAS_GELU,
  NOVA_OP_FUSED_MATMUL_SOFTMAX,
  NOVA_OP_FUSED_CONV_BIAS_RELU,
  NOVA_OP_FUSED_ATTENTION,
  NOVA_OP_COUNT,
} NovaOpType;

/* =========================================================================
 * Tensor
 * ========================================================================= */
typedef struct NovaTensor {
  uint32_t id;
  NovaDType dtype;
  uint32_t ndim;
  int64_t shape[NOVA_MAX_DIMS];
  int64_t strides[NOVA_MAX_DIMS]; /* byte strides */
  void *data;                     /* NULL = not yet allocated */
  size_t nbytes;
  uint32_t ref_count; /* for buffer reuse tracking */
  bool is_alias;      /* shares memory with another tensor */
  uint32_t alias_of;  /* id of aliased tensor (if is_alias) */
  /* Lifetime tracking for memory planner */
  int32_t first_use; /* topo order index */
  int32_t last_use;  /* topo order index */
  bool is_parameter; /* weights — never freed */
  bool is_output;    /* graph output — never freed mid-graph */
} NovaTensor;

/* =========================================================================
 * Node
 * ========================================================================= */
typedef struct NovaNode {
  uint32_t id;
  NovaOpType op;
  char name[64];

  /* Inputs / outputs (tensor ids) */
  uint32_t inputs[NOVA_MAX_INPUTS];
  uint32_t num_inputs;
  uint32_t outputs[NOVA_MAX_OUTPUTS];
  uint32_t num_outputs;

  /* Op-specific params (union keeps struct small) */
  union {
    struct {
      int stride_h, stride_w, pad_h, pad_w, groups;
    } conv;
    struct {
      int axis;
    } softmax;
    struct {
      float eps;
    } layernorm;
    struct {
      int num_heads;
      float scale;
    } attention;
  } params;

  /* Fusion metadata */
  bool is_fused;       /* this node absorbed into another */
  uint32_t fused_into; /* node id that absorbed this one */
  uint32_t fused_ops[NOVA_MAX_FUSED_OPS];
  uint32_t num_fused_ops;

  /* Scheduling metadata */
  int32_t topo_order; /* assigned during topo sort */
  bool scheduled;
  bool executed;

  /* Perf counters (filled by instrumentation) */
  uint64_t exec_ns; /* nanoseconds */
  uint64_t mem_bytes_read;
  uint64_t mem_bytes_written;
} NovaNode;

/* =========================================================================
 * Backend
 * ========================================================================= */
typedef enum {
  NOVA_BACKEND_CPU = 0,
  NOVA_BACKEND_CUDA = 1,
  NOVA_BACKEND_METAL = 2,
  NOVA_BACKEND_VULKAN = 3,
} NovaBackendType;

typedef struct NovaBackend {
  NovaBackendType type;
  const char *name;

  /* Core interface — tensors is the graph's flat tensor array */
  void (*execute)(struct NovaBackend *b, NovaNode *n, NovaTensor *tensors);
  void *(*alloc)(struct NovaBackend *b, size_t bytes, size_t alignment);
  void (*dealloc)(struct NovaBackend *b, void *ptr);
  void (*synchronize)(struct NovaBackend *b);
  bool (*is_available)(void);

  /* Optional: batch dispatch */
  void (*execute_batch)(struct NovaBackend *b, NovaNode **nodes, uint32_t count,
                        NovaTensor *tensors);

  void *priv; /* backend private data */
} NovaBackend;

/* =========================================================================
 * Arena allocator
 * ========================================================================= */
typedef struct NovaArena {
  uint8_t *base;
  size_t capacity;
  size_t used;
  size_t peak;
  uint32_t num_allocs;
  uint32_t num_frees; /* arenas don't free individually; tracked for stats */
} NovaArena;

/* =========================================================================
 * Graph
 * ========================================================================= */
typedef struct NovaGraph {
  uint32_t id;
  char name[64];

  NovaNode *nodes; /* flat array, capacity = max_nodes */
  uint32_t num_nodes;
  uint32_t max_nodes;

  NovaTensor *tensors; /* flat array, capacity = max_tensors */
  uint32_t num_tensors;
  uint32_t max_tensors;

  /* Topological order (indices into nodes[]) */
  uint32_t *topo_order;
  uint32_t topo_len;

  /* Memory planning */
  NovaArena workspace;   /* scratch arena for activations */
  NovaArena param_arena; /* parameter arena — never reset */

  /* Attached backend */
  NovaBackend *backend;

  /* Flags */
  bool optimized; /* optimization pass has run */
  bool memory_planned;

  /* Instrumentation */
  uint64_t total_exec_ns;
  uint32_t kernel_launches;
  uint32_t fusions_applied;
} NovaGraph;

/* =========================================================================
 * Instrumentation
 * ========================================================================= */
typedef struct NovaTraceEvent {
  uint32_t node_id;
  uint64_t ts_begin; /* nanoseconds */
  uint64_t ts_end;
  uint64_t mem_read;
  uint64_t mem_written;
} NovaTraceEvent;

typedef struct NovaTrace {
  NovaTraceEvent *events;
  uint32_t capacity;
  uint32_t count;
  bool enabled;
} NovaTrace;

/* =========================================================================
 * Public API — declared here, defined in separate .c files
 * ========================================================================= */

/* Graph lifecycle */
NovaGraph *nova_graph_create(const char *name, uint32_t max_nodes,
                             uint32_t max_tensors);
void nova_graph_destroy(NovaGraph *g);
void nova_graph_set_backend(NovaGraph *g, NovaBackend *b);

/* Tensor API */
uint32_t nova_tensor_add(NovaGraph *g, NovaDType dtype, uint32_t ndim,
                         const int64_t *shape, bool is_parameter);
NovaTensor *nova_tensor_get(NovaGraph *g, uint32_t id);
size_t nova_tensor_nbytes(const NovaTensor *t);

/* Node API */
uint32_t nova_node_add(NovaGraph *g, NovaOpType op, const char *name,
                       const uint32_t *inputs, uint32_t num_in,
                       const uint32_t *outputs, uint32_t num_out);
NovaNode *nova_node_get(NovaGraph *g, uint32_t id);

/* Graph optimization */
NovaStatus nova_graph_optimize(NovaGraph *g);
NovaStatus nova_graph_topo_sort(NovaGraph *g);
NovaStatus nova_graph_dead_node_elim(NovaGraph *g);

/* Fusion engine */
bool nova_can_fuse(const NovaNode *a, const NovaNode *b);
NovaStatus nova_fusion_pass(NovaGraph *g);

/* Memory planner */
NovaStatus nova_memory_plan(NovaGraph *g);
NovaStatus nova_memory_allocate(NovaGraph *g);

/* Execution */
NovaStatus nova_graph_execute(NovaGraph *g);

/* Arena */
NovaArena nova_arena_create(size_t capacity);
void *nova_arena_alloc(NovaArena *a, size_t bytes, size_t align);
void nova_arena_reset(NovaArena *a);
void nova_arena_destroy(NovaArena *a);

/* Instrumentation */
NovaTrace *nova_trace_create(uint32_t capacity);
void nova_trace_destroy(NovaTrace *t);
void nova_trace_begin(NovaTrace *t, uint32_t node_id);
void nova_trace_end(NovaTrace *t, uint32_t node_id, uint64_t mem_read,
                    uint64_t mem_written);
void nova_trace_print(const NovaTrace *t, const NovaGraph *g);

/* Backends */
NovaBackend *nova_backend_cpu(void);
NovaBackend *nova_backend_cuda_stub(void);
NovaBackend *nova_backend_metal_stub(void);
NovaBackend *nova_backend_vulkan_stub(void);

/* Utilities */
const char *nova_op_name(NovaOpType op);
const char *nova_status_str(NovaStatus s);
uint64_t nova_clock_ns(void);

#endif /* NOVA_H */
