/**
 * nova_mobile_codegen.c - iOS & Android Code Generator Implementation
 *
 * Generates native Swift/SwiftUI and Kotlin/Compose code from Nova specs.
 */

#include "nova_mobile_codegen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

// ═══════════════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════════════

static void ensure_dir(const char *path) {
  char tmp[512];
  snprintf(tmp, sizeof(tmp), "%s", path);
  for (char *p = tmp + 1; *p; p++) {
    if (*p == '/') {
      *p = '\0';
      mkdir(tmp, 0755);
      *p = '/';
    }
  }
  mkdir(tmp, 0755);
}

static NovaGeneratedFile *add_file(NovaMobileProject *proj,
                                   const char *filename, const char *lang) {
  if (proj->file_count >= proj->capacity) {
    proj->capacity = proj->capacity ? proj->capacity * 2 : 32;
    proj->files =
        realloc(proj->files, proj->capacity * sizeof(NovaGeneratedFile));
  }
  NovaGeneratedFile *f = &proj->files[proj->file_count++];
  memset(f, 0, sizeof(*f));
  strncpy(f->filename, filename, sizeof(f->filename) - 1);
  strncpy(f->language, lang, sizeof(f->language) - 1);
  return f;
}

static void set_code(NovaGeneratedFile *f, const char *code) {
  f->code_len = strlen(code);
  f->code = malloc(f->code_len + 1);
  memcpy(f->code, code, f->code_len + 1);
}

__attribute__((unused)) static void append_code(NovaGeneratedFile *f,
                                                const char *code) {
  size_t extra = strlen(code);
  f->code = realloc(f->code, f->code_len + extra + 1);
  memcpy(f->code + f->code_len, code, extra + 1);
  f->code_len += extra;
}

// ═══════════════════════════════════════════════════════════════════════════
// Project Lifecycle
// ═══════════════════════════════════════════════════════════════════════════

NovaMobileProject *nova_mobile_create_project(const NovaMobileConfig *cfg) {
  NovaMobileProject *proj = calloc(1, sizeof(NovaMobileProject));
  snprintf(proj->project_dir, sizeof(proj->project_dir), "%s/%s",
           cfg->output_dir, cfg->app_name);
  return proj;
}

void nova_mobile_destroy_project(NovaMobileProject *proj) {
  if (!proj)
    return;
  for (int i = 0; i < proj->file_count; i++)
    free(proj->files[i].code);
  free(proj->files);
  free(proj);
}

// ═══════════════════════════════════════════════════════════════════════════
// iOS / Swift Generation
// ═══════════════════════════════════════════════════════════════════════════

int nova_mobile_gen_swift_model(NovaMobileProject *proj, const char *name,
                                const char *fields) {
  char fname[256];
  snprintf(fname, sizeof(fname), "ios/Models/%s.swift", name);
  NovaGeneratedFile *f = add_file(proj, fname, "swift");

  char buf[4096];
  snprintf(buf, sizeof(buf),
           "//\n// %s.swift - Generated by Nova Mobile Codegen\n//\n\n"
           "import Foundation\n\n"
           "struct %s: Codable, Identifiable, Hashable {\n"
           "    let id: UUID\n"
           "%s"
           "\n"
           "    init(%s) {\n"
           "        self.id = UUID()\n"
           "        // TODO: Initialize fields\n"
           "    }\n"
           "}\n",
           name, name, fields, fields);
  set_code(f, buf);
  return 0;
}

int nova_mobile_gen_swiftui_view(NovaMobileProject *proj, const char *name,
                                 const char *body_spec) {
  char fname[256];
  snprintf(fname, sizeof(fname), "ios/Views/%sView.swift", name);
  NovaGeneratedFile *f = add_file(proj, fname, "swift");

  char buf[4096];
  snprintf(buf, sizeof(buf),
           "//\n// %sView.swift - Generated by Nova Mobile Codegen\n//\n\n"
           "import SwiftUI\n\n"
           "struct %sView: View {\n"
           "    @StateObject private var viewModel = %sViewModel()\n\n"
           "    var body: some View {\n"
           "        NavigationStack {\n"
           "            %s\n"
           "        }\n"
           "        .navigationTitle(\"%s\")\n"
           "    }\n"
           "}\n\n"
           "class %sViewModel: ObservableObject {\n"
           "    @Published var isLoading = false\n"
           "    @Published var error: String?\n\n"
           "    func load() async {\n"
           "        isLoading = true\n"
           "        defer { isLoading = false }\n"
           "        // TODO: Load data\n"
           "    }\n"
           "}\n\n"
           "#Preview {\n"
           "    %sView()\n"
           "}\n",
           name, name, name,
           body_spec ? body_spec : "Text(\"Hello from Nova!\")", name, name,
           name);
  set_code(f, buf);
  return 0;
}

int nova_mobile_gen_ios_app_delegate(NovaMobileProject *proj) {
  NovaGeneratedFile *f = add_file(proj, "ios/App/App.swift", "swift");
  set_code(f, "//\n// App.swift - Generated by Nova Mobile Codegen\n//\n\n"
              "import SwiftUI\n\n"
              "@main\n"
              "struct NovaApp: App {\n"
              "    var body: some Scene {\n"
              "        WindowGroup {\n"
              "            ContentView()\n"
              "        }\n"
              "    }\n"
              "}\n");
  return 0;
}

int nova_mobile_gen_ios_info_plist(NovaMobileProject *proj,
                                   const NovaMobileConfig *cfg) {
  NovaGeneratedFile *f = add_file(proj, "ios/Info.plist", "xml");
  char buf[2048];
  snprintf(buf, sizeof(buf),
           "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
           "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\"\n"
           "  \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
           "<plist version=\"1.0\">\n<dict>\n"
           "  <key>CFBundleIdentifier</key>\n"
           "  <string>%s</string>\n"
           "  <key>CFBundleName</key>\n"
           "  <string>%s</string>\n"
           "  <key>CFBundleVersion</key>\n"
           "  <string>1.0</string>\n"
           "  <key>CFBundleShortVersionString</key>\n"
           "  <string>1.0.0</string>\n"
           "  <key>MinimumOSVersion</key>\n"
           "  <string>%s</string>\n"
           "  <key>UILaunchScreen</key>\n"
           "  <dict/>\n"
           "</dict>\n</plist>\n",
           cfg->bundle_id, cfg->app_name, cfg->min_ios_version);
  set_code(f, buf);
  return 0;
}

int nova_mobile_gen_xcode_project(NovaMobileProject *proj,
                                  const NovaMobileConfig *cfg) {
  (void)cfg;
  NovaGeneratedFile *f = add_file(proj, "ios/project.pbxproj.stub", "text");
  set_code(f, "// Xcode project stub - Generated by Nova Mobile Codegen\n"
              "// Use: xcodegen generate --spec project.yml\n"
              "// Or open in Xcode and add sources manually.\n");
  return 0;
}

// ═══════════════════════════════════════════════════════════════════════════
// Android / Kotlin Generation
// ═══════════════════════════════════════════════════════════════════════════

int nova_mobile_gen_kotlin_model(NovaMobileProject *proj, const char *name,
                                 const char *fields) {
  char fname[256];
  snprintf(fname, sizeof(fname), "android/app/src/main/java/models/%s.kt",
           name);
  NovaGeneratedFile *f = add_file(proj, fname, "kotlin");

  char buf[4096];
  snprintf(buf, sizeof(buf),
           "// %s.kt - Generated by Nova Mobile Codegen\n\n"
           "package models\n\n"
           "import java.util.UUID\n\n"
           "data class %s(\n"
           "    val id: String = UUID.randomUUID().toString(),\n"
           "%s"
           ")\n",
           name, name, fields);
  set_code(f, buf);
  return 0;
}

int nova_mobile_gen_compose_screen(NovaMobileProject *proj, const char *name,
                                   const char *body_spec) {
  char fname[256];
  snprintf(fname, sizeof(fname), "android/app/src/main/java/ui/%sScreen.kt",
           name);
  NovaGeneratedFile *f = add_file(proj, fname, "kotlin");

  char buf[4096];
  snprintf(buf, sizeof(buf),
           "// %sScreen.kt - Generated by Nova Mobile Codegen\n\n"
           "package ui\n\n"
           "import androidx.compose.foundation.layout.*\n"
           "import androidx.compose.material3.*\n"
           "import androidx.compose.runtime.*\n"
           "import androidx.compose.ui.Modifier\n"
           "import androidx.compose.ui.unit.dp\n"
           "import androidx.lifecycle.viewmodel.compose.viewModel\n\n"
           "@OptIn(ExperimentalMaterial3Api::class)\n"
           "@Composable\n"
           "fun %sScreen(\n"
           "    viewModel: %sViewModel = viewModel()\n"
           ") {\n"
           "    val uiState by viewModel.uiState.collectAsState()\n\n"
           "    Scaffold(\n"
           "        topBar = {\n"
           "            TopAppBar(title = { Text(\"%s\") })\n"
           "        }\n"
           "    ) { padding ->\n"
           "        Column(\n"
           "            modifier = Modifier.padding(padding).padding(16.dp)\n"
           "        ) {\n"
           "            %s\n"
           "        }\n"
           "    }\n"
           "}\n",
           name, name, name, name,
           body_spec ? body_spec : "Text(\"Hello from Nova!\")");
  set_code(f, buf);
  return 0;
}

int nova_mobile_gen_android_activity(NovaMobileProject *proj) {
  NovaGeneratedFile *f =
      add_file(proj, "android/app/src/main/java/MainActivity.kt", "kotlin");
  set_code(f, "// MainActivity.kt - Generated by Nova Mobile Codegen\n\n"
              "import android.os.Bundle\n"
              "import androidx.activity.ComponentActivity\n"
              "import androidx.activity.compose.setContent\n"
              "import androidx.compose.material3.MaterialTheme\n"
              "import ui.MainScreen\n\n"
              "class MainActivity : ComponentActivity() {\n"
              "    override fun onCreate(savedInstanceState: Bundle?) {\n"
              "        super.onCreate(savedInstanceState)\n"
              "        setContent {\n"
              "            MaterialTheme {\n"
              "                MainScreen()\n"
              "            }\n"
              "        }\n"
              "    }\n"
              "}\n");
  return 0;
}

int nova_mobile_gen_android_manifest(NovaMobileProject *proj,
                                     const NovaMobileConfig *cfg) {
  NovaGeneratedFile *f =
      add_file(proj, "android/app/src/main/AndroidManifest.xml", "xml");
  char buf[2048];
  snprintf(
      buf, sizeof(buf),
      "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
      "<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\n"
      "    package=\"%s\">\n\n"
      "    <uses-permission android:name=\"android.permission.INTERNET\"/>\n\n"
      "    <application\n"
      "        android:allowBackup=\"true\"\n"
      "        android:label=\"%s\"\n"
      "        android:supportsRtl=\"true\"\n"
      "        android:theme=\"@style/Theme.Material3.DayNight\">\n"
      "        <activity\n"
      "            android:name=\".MainActivity\"\n"
      "            android:exported=\"true\">\n"
      "            <intent-filter>\n"
      "                <action android:name=\"android.intent.action.MAIN\"/>\n"
      "                <category "
      "android:name=\"android.intent.category.LAUNCHER\"/>\n"
      "            </intent-filter>\n"
      "        </activity>\n"
      "    </application>\n"
      "</manifest>\n",
      cfg->package_name, cfg->app_name);
  set_code(f, buf);
  return 0;
}

int nova_mobile_gen_gradle_build(NovaMobileProject *proj,
                                 const NovaMobileConfig *cfg) {
  NovaGeneratedFile *f =
      add_file(proj, "android/app/build.gradle.kts", "kotlin");
  char buf[4096];
  snprintf(
      buf, sizeof(buf),
      "// build.gradle.kts - Generated by Nova Mobile Codegen\n\n"
      "plugins {\n"
      "    id(\"com.android.application\")\n"
      "    id(\"org.jetbrains.kotlin.android\")\n"
      "}\n\n"
      "android {\n"
      "    namespace = \"%s\"\n"
      "    compileSdk = %d\n\n"
      "    defaultConfig {\n"
      "        applicationId = \"%s\"\n"
      "        minSdk = %d\n"
      "        targetSdk = %d\n"
      "        versionCode = 1\n"
      "        versionName = \"1.0\"\n"
      "    }\n\n"
      "    buildFeatures {\n"
      "        compose = true\n"
      "    }\n\n"
      "    composeOptions {\n"
      "        kotlinCompilerExtensionVersion = \"1.5.4\"\n"
      "    }\n"
      "}\n\n"
      "dependencies {\n"
      "    implementation(\"androidx.core:core-ktx:1.12.0\")\n"
      "    implementation(\"androidx.lifecycle:lifecycle-runtime-ktx:2.7.0\")\n"
      "    implementation(\"androidx.activity:activity-compose:1.8.2\")\n"
      "    "
      "implementation(platform(\"androidx.compose:compose-bom:2024.01.00\"))\n"
      "    implementation(\"androidx.compose.ui:ui\")\n"
      "    implementation(\"androidx.compose.material3:material3\")\n"
      "    implementation(\"androidx.compose.ui:ui-tooling-preview\")\n"
      "    "
      "implementation(\"androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0\")"
      "\n"
      "%s"
      "}\n",
      cfg->package_name, cfg->target_android_sdk, cfg->package_name,
      cfg->min_android_sdk, cfg->target_android_sdk,
      cfg->use_room
          ? "    implementation(\"androidx.room:room-runtime:2.6.1\")\n"
            "    annotationProcessor(\"androidx.room:room-compiler:2.6.1\")\n"
          : "");
  set_code(f, buf);
  return 0;
}

// ═══════════════════════════════════════════════════════════════════════════
// Shared Layers
// ═══════════════════════════════════════════════════════════════════════════

int nova_mobile_gen_network_layer(NovaMobileProject *proj,
                                  NovaMobilePlatform platform) {
  if (platform == NOVA_MOBILE_IOS || platform == NOVA_MOBILE_BOTH) {
    NovaGeneratedFile *f =
        add_file(proj, "ios/Network/APIClient.swift", "swift");
    set_code(
        f,
        "// APIClient.swift - Generated by Nova Mobile Codegen\n\n"
        "import Foundation\n\n"
        "actor APIClient {\n"
        "    static let shared = APIClient()\n"
        "    private let session: URLSession\n"
        "    private let baseURL: URL\n\n"
        "    init(baseURL: URL = URL(string: \"https://api.example.com\")!) {\n"
        "        self.baseURL = baseURL\n"
        "        let config = URLSessionConfiguration.default\n"
        "        config.timeoutIntervalForRequest = 30\n"
        "        self.session = URLSession(configuration: config)\n"
        "    }\n\n"
        "    func get<T: Decodable>(_ path: String) async throws -> T {\n"
        "        let url = baseURL.appendingPathComponent(path)\n"
        "        let (data, _) = try await session.data(from: url)\n"
        "        return try JSONDecoder().decode(T.self, from: data)\n"
        "    }\n\n"
        "    func post<T: Codable, R: Decodable>(_ path: String, body: T) "
        "async throws -> R {\n"
        "        let url = baseURL.appendingPathComponent(path)\n"
        "        var request = URLRequest(url: url)\n"
        "        request.httpMethod = \"POST\"\n"
        "        request.httpBody = try JSONEncoder().encode(body)\n"
        "        request.setValue(\"application/json\", forHTTPHeaderField: "
        "\"Content-Type\")\n"
        "        let (data, _) = try await session.data(for: request)\n"
        "        return try JSONDecoder().decode(R.self, from: data)\n"
        "    }\n"
        "}\n");
  }

  if (platform == NOVA_MOBILE_ANDROID || platform == NOVA_MOBILE_BOTH) {
    NovaGeneratedFile *f = add_file(
        proj, "android/app/src/main/java/network/ApiClient.kt", "kotlin");
    set_code(f,
             "// ApiClient.kt - Generated by Nova Mobile Codegen\n\n"
             "package network\n\n"
             "import kotlinx.coroutines.Dispatchers\n"
             "import kotlinx.coroutines.withContext\n"
             "import java.net.HttpURLConnection\n"
             "import java.net.URL\n\n"
             "object ApiClient {\n"
             "    private const val BASE_URL = \"https://api.example.com\"\n\n"
             "    suspend fun get(path: String): String = "
             "withContext(Dispatchers.IO) {\n"
             "        val url = URL(\"$BASE_URL/$path\")\n"
             "        val conn = url.openConnection() as HttpURLConnection\n"
             "        conn.requestMethod = \"GET\"\n"
             "        conn.connectTimeout = 30000\n"
             "        conn.inputStream.bufferedReader().readText()\n"
             "    }\n\n"
             "    suspend fun post(path: String, body: String): String = "
             "withContext(Dispatchers.IO) {\n"
             "        val url = URL(\"$BASE_URL/$path\")\n"
             "        val conn = url.openConnection() as HttpURLConnection\n"
             "        conn.requestMethod = \"POST\"\n"
             "        conn.doOutput = true\n"
             "        conn.setRequestProperty(\"Content-Type\", "
             "\"application/json\")\n"
             "        conn.outputStream.write(body.toByteArray())\n"
             "        conn.inputStream.bufferedReader().readText()\n"
             "    }\n"
             "}\n");
  }
  return 0;
}

int nova_mobile_gen_storage_layer(NovaMobileProject *proj,
                                  NovaMobilePlatform platform) {
  if (platform == NOVA_MOBILE_IOS || platform == NOVA_MOBILE_BOTH) {
    NovaGeneratedFile *f =
        add_file(proj, "ios/Storage/StorageManager.swift", "swift");
    set_code(f, "// StorageManager.swift - Generated by Nova Mobile Codegen\n\n"
                "import Foundation\n\n"
                "class StorageManager {\n"
                "    static let shared = StorageManager()\n"
                "    private let defaults = UserDefaults.standard\n\n"
                "    func save<T: Codable>(_ value: T, forKey key: String) {\n"
                "        if let data = try? JSONEncoder().encode(value) {\n"
                "            defaults.set(data, forKey: key)\n"
                "        }\n"
                "    }\n\n"
                "    func load<T: Codable>(forKey key: String) -> T? {\n"
                "        guard let data = defaults.data(forKey: key) else { "
                "return nil }\n"
                "        return try? JSONDecoder().decode(T.self, from: data)\n"
                "    }\n\n"
                "    func delete(forKey key: String) {\n"
                "        defaults.removeObject(forKey: key)\n"
                "    }\n"
                "}\n");
  }

  if (platform == NOVA_MOBILE_ANDROID || platform == NOVA_MOBILE_BOTH) {
    NovaGeneratedFile *f = add_file(
        proj, "android/app/src/main/java/storage/StorageManager.kt", "kotlin");
    set_code(f,
             "// StorageManager.kt - Generated by Nova Mobile Codegen\n\n"
             "package storage\n\n"
             "import android.content.Context\n"
             "import android.content.SharedPreferences\n\n"
             "class StorageManager(context: Context) {\n"
             "    private val prefs: SharedPreferences =\n"
             "        context.getSharedPreferences(\"nova_storage\", "
             "Context.MODE_PRIVATE)\n\n"
             "    fun saveString(key: String, value: String) {\n"
             "        prefs.edit().putString(key, value).apply()\n"
             "    }\n\n"
             "    fun loadString(key: String): String? = prefs.getString(key, "
             "null)\n\n"
             "    fun delete(key: String) = prefs.edit().remove(key).apply()\n"
             "}\n");
  }
  return 0;
}

// ═══════════════════════════════════════════════════════════════════════════
// Write to Disk
// ═══════════════════════════════════════════════════════════════════════════

int nova_mobile_write_project(const NovaMobileProject *proj) {
  if (!proj || proj->file_count == 0)
    return -1;

  printf("📱 Writing mobile project: %s (%d files)\n", proj->project_dir,
         proj->file_count);

  for (int i = 0; i < proj->file_count; i++) {
    const NovaGeneratedFile *f = &proj->files[i];
    char path[1024];
    snprintf(path, sizeof(path), "%s/%s", proj->project_dir, f->filename);

    // Ensure parent directory exists
    char dir[1024];
    strncpy(dir, path, sizeof(dir));
    char *last_slash = strrchr(dir, '/');
    if (last_slash) {
      *last_slash = '\0';
      ensure_dir(dir);
    }

    FILE *fp = fopen(path, "w");
    if (!fp) {
      fprintf(stderr, "❌ Cannot write: %s\n", path);
      continue;
    }
    fwrite(f->code, 1, f->code_len, fp);
    fclose(fp);
    printf("  ✅ %s (%zu bytes)\n", f->filename, f->code_len);
  }

  printf("📱 Project written successfully!\n");
  return 0;
}

// ═══════════════════════════════════════════════════════════════════════════
// Build Commands
// ═══════════════════════════════════════════════════════════════════════════

int nova_mobile_build_ios(const NovaMobileProject *proj) {
  char cmd[1024];
  snprintf(cmd, sizeof(cmd),
           "xcodebuild -project %s/ios/*.xcodeproj "
           "-scheme NovaApp -sdk iphoneos "
           "-configuration Release 2>&1",
           proj->project_dir);
  printf("🍎 Building iOS: %s\n", cmd);
  return system(cmd);
}

int nova_mobile_build_android(const NovaMobileProject *proj) {
  char cmd[1024];
  snprintf(cmd, sizeof(cmd), "cd %s/android && ./gradlew assembleRelease 2>&1",
           proj->project_dir);
  printf("🤖 Building Android: %s\n", cmd);
  return system(cmd);
}
