#ifndef NOVA_JIT_TAGS_H
#define NOVA_JIT_TAGS_H

/* JITMode definition */
#define NOVA_JIT_JITMODE_LAZY 0
#define NOVA_JIT_JITMODE_EAGER 1
#define NOVA_JIT_JITMODE_ADAPTIVE 2

/* OptimizationLevel definition */
#define NOVA_JIT_OPTIMIZATIONLEVEL_NOOPTIMIZATION 3
#define NOVA_JIT_OPTIMIZATIONLEVEL_BASICOPTIMIZATION 4
#define NOVA_JIT_OPTIMIZATIONLEVEL_STANDARDOPTIMIZATION 5
#define NOVA_JIT_OPTIMIZATIONLEVEL_AGGRESSIVEOPTIMIZATION 6

/* TargetArch definition */
#define NOVA_JIT_TARGETARCH_X86_64 7
#define NOVA_JIT_TARGETARCH_ARM64 8
#define NOVA_JIT_TARGETARCH_RISCV64 9

/* CompilationStatus definition */
#define NOVA_JIT_COMPILATIONSTATUS_NOTCOMPILED 10
#define NOVA_JIT_COMPILATIONSTATUS_COMPILING 11
#define NOVA_JIT_COMPILATIONSTATUS_COMPILED 12
#define NOVA_JIT_COMPILATIONSTATUS_FAILED 13

/* OptLevel definition */
#define NOVA_JIT_OPTLEVEL_NONE 14
#define NOVA_JIT_OPTLEVEL_SPEED 15
#define NOVA_JIT_OPTLEVEL_SPEEDANDSIZE 16

#endif

