#ifndef NOVA_LIVE_RANGE_TAGS_H
#define NOVA_LIVE_RANGE_TAGS_H

/* UseKind definition */
#define NOVA_LIVE_RANGE_USEKIND_READ 0
#define NOVA_LIVE_RANGE_USEKIND_WRITE 1
#define NOVA_LIVE_RANGE_USEKIND_READWRITE 2

#endif

