#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

// Error Model for Nova - Phase D.2
// Result<T,E> ergonomics with ? operator

// === RESULT TYPE INFRASTRUCTURE ===

// Result<T,E> enum - this would be generated by the compiler
typedef enum {
    RESULT_OK,
    RESULT_ERR
} nova_result_kind_t;

// Generic Result structure (simplified for testing)
typedef struct {
    nova_result_kind_t kind;
    union {
        void* ok_value;    // T
        void* err_value;   // E
    } data;
} nova_result_t;

// Constructor functions
nova_result_t* nova_result_ok(void* value) {
    nova_result_t* res = malloc(sizeof(nova_result_t));
    res->kind = RESULT_OK;
    res->data.ok_value = value;
    return res;
}

nova_result_t* nova_result_err(void* error) {
    nova_result_t* res = malloc(sizeof(nova_result_t));
    res->kind = RESULT_ERR;
    res->data.err_value = error;
    return res;
}

// === ? OPERATOR LOWERING ===

// Simplified AST for ? operator testing
typedef enum {
    EXPR_RESULT_CALL,
    EXPR_RESULT_PROPAGATE,  // represents x?
    EXPR_LITERAL
} nova_expr_kind_t;

typedef struct nova_expr nova_expr_t;

typedef struct {
    nova_expr_t* func;
    nova_expr_t** args;
    size_t arg_count;
} nova_call_expr_t;

typedef struct {
    nova_expr_t* target;  // expression being propagated
} nova_propagate_expr_t;

typedef struct {
    int value;
} nova_literal_expr_t;

typedef struct nova_expr {
    nova_expr_kind_t kind;
    union {
        nova_call_expr_t call;
        nova_propagate_expr_t propagate;
        nova_literal_expr_t literal;
    } data;
} nova_expr_t;

// Lowering context for ? operator
typedef struct {
    nova_expr_t** lowered_stmts;
    size_t stmt_count;
    size_t stmt_capacity;
    int current_temp_var;
} nova_lowering_context_t;

nova_lowering_context_t* nova_lowering_context_create() {
    nova_lowering_context_t* ctx = calloc(1, sizeof(nova_lowering_context_t));
    ctx->stmt_count = 0;
    ctx->stmt_capacity = 16;
    ctx->lowered_stmts = malloc(sizeof(nova_expr_t*) * ctx->stmt_capacity);
    ctx->current_temp_var = 0;
    return ctx;
}

void nova_lowering_context_destroy(nova_lowering_context_t* ctx) {
    free(ctx->lowered_stmts);
    free(ctx);
}

static void add_lowered_stmt(nova_lowering_context_t* ctx, nova_expr_t* stmt) {
    if (ctx->stmt_count >= ctx->stmt_capacity) {
        ctx->stmt_capacity *= 2;
        ctx->lowered_stmts = realloc(ctx->lowered_stmts, sizeof(nova_expr_t*) * ctx->stmt_capacity);
    }
    ctx->lowered_stmts[ctx->stmt_count++] = stmt;
}

// Lower ? operator to early return pattern
nova_expr_t* nova_lower_propagate(nova_lowering_context_t* ctx, nova_expr_t* expr) {
    // The ? operator desugars to:
    // match expr {
    //     Ok(v) => v,
    //     Err(e) => return Err(e)
    // }

    // For now, create a simplified lowering:
    // let temp = expr;
    // if temp.is_err() { return temp; }
    // temp.unwrap()

    // Create temp variable assignment
    nova_expr_t* temp_var = malloc(sizeof(nova_expr_t));
    temp_var->kind = EXPR_LITERAL;
    temp_var->data.literal.value = ctx->current_temp_var++;

    // Add: let temp = expr;
    nova_expr_t* temp_assign = malloc(sizeof(nova_expr_t));
    temp_assign->kind = EXPR_RESULT_CALL;  // simplified assignment
    temp_assign->data.call.func = temp_var;
    temp_assign->data.call.args = &expr;
    temp_assign->data.call.arg_count = 1;

    add_lowered_stmt(ctx, temp_assign);

    // Return the temp variable (simplified - real implementation would unwrap)
    return temp_var;
}

// Lower expressions with ? operator
nova_expr_t* nova_lower_expr(nova_lowering_context_t* ctx, nova_expr_t* expr) {
    if (!expr) return NULL;

    switch (expr->kind) {
        case EXPR_RESULT_PROPAGATE: {
            // This is x? - lower it
            nova_expr_t* target = nova_lower_expr(ctx, expr->data.propagate.target);
            return nova_lower_propagate(ctx, target);
        }

        case EXPR_RESULT_CALL: {
            // Lower arguments that might contain ?
            for (size_t i = 0; i < expr->data.call.arg_count; i++) {
                expr->data.call.args[i] = nova_lower_expr(ctx, expr->data.call.args[i]);
            }
            return expr;
        }

        default:
            return expr;
    }
}

// === TYPE CHECKING FOR ERROR PROPAGATION ===

typedef enum {
    TYPE_RESULT,  // Result<T,E>
    TYPE_INT,
    TYPE_STRING
} nova_type_kind_t;

typedef struct nova_type nova_type_t;

typedef struct {
    nova_type_t* ok_type;   // T
    nova_type_t* err_type;  // E
} nova_result_type_t;

struct nova_type {
    nova_type_kind_t kind;
    union {
        nova_result_type_t result;
        // other types...
    } data;
};

// Type checking context
typedef struct {
    nova_type_t** function_returns;  // stack of function return types
    size_t return_count;
} nova_typecheck_context_t;

nova_typecheck_context_t* nova_typecheck_context_create() {
    nova_typecheck_context_t* ctx = calloc(1, sizeof(nova_typecheck_context_t));
    ctx->return_count = 0;
    ctx->function_returns = NULL;
    return ctx;
}

void nova_typecheck_context_destroy(nova_typecheck_context_t* ctx) {
    free(ctx->function_returns);
    free(ctx);
}

// Check if expression can be propagated (? operator)
bool nova_can_propagate(nova_typecheck_context_t* ctx, nova_type_t* expr_type) {
    if (!expr_type || expr_type->kind != TYPE_RESULT) {
        return false;
    }

    // Check if current function returns compatible Result type
    if (ctx->return_count == 0) {
        return false;  // not in a function
    }

    nova_type_t* func_return = ctx->function_returns[ctx->return_count - 1];
    if (func_return->kind != TYPE_RESULT) {
        return false;  // function doesn't return Result
    }

    // Check error type compatibility
    // Simplified: assume error types match
    return true;
}

// === TEST INFRASTRUCTURE ===

void nova_expr_print(nova_expr_t* expr) {
    if (!expr) {
        printf("<null>");
        return;
    }

    switch (expr->kind) {
        case EXPR_LITERAL:
            printf("literal(%d)", expr->data.literal.value);
            break;
        case EXPR_RESULT_CALL:
            printf("call(");
            nova_expr_print(expr->data.call.func);
            for (size_t i = 0; i < expr->data.call.arg_count; i++) {
                printf(", ");
                nova_expr_print(expr->data.call.args[i]);
            }
            printf(")");
            break;
        case EXPR_RESULT_PROPAGATE:
            nova_expr_print(expr->data.propagate.target);
            printf("?");
            break;
        default:
            printf("<unknown>");
            break;
    }
}

void nova_test_error_model() {
    printf("🧪 Testing Nova Error Model (D.2)\n");
    printf("==================================\n\n");

    // Test Result type construction
    printf("1. Testing Result<T,E> construction...\n");

    nova_result_t* ok_result = nova_result_ok((void*)42);
    nova_result_t* err_result = nova_result_err((void*)"error");

    printf("   Ok(42): %s\n", ok_result->kind == RESULT_OK ? "✓" : "✗");
    printf("   Err(\"error\"): %s\n", err_result->kind == RESULT_ERR ? "✓" : "✗");

    // Test ? operator lowering
    printf("2. Testing ? operator lowering...\n");

    nova_lowering_context_t* ctx = nova_lowering_context_create();

    // Create: parse_int(s)?
    nova_expr_t* s_var = malloc(sizeof(nova_expr_t));
    s_var->kind = EXPR_LITERAL;
    s_var->data.literal.value = 1;  // represents variable 's'

    nova_expr_t* parse_call = malloc(sizeof(nova_expr_t));
    parse_call->kind = EXPR_RESULT_CALL;
    parse_call->data.call.func = s_var;  // simplified
    parse_call->data.call.args = NULL;
    parse_call->data.call.arg_count = 0;

    nova_expr_t* propagate_expr = malloc(sizeof(nova_expr_t));
    propagate_expr->kind = EXPR_RESULT_PROPAGATE;
    propagate_expr->data.propagate.target = parse_call;

    // Lower the expression
    nova_expr_t* lowered = nova_lower_expr(ctx, propagate_expr);

    printf("   Original: ");
    nova_expr_print(propagate_expr);
    printf("\n");

    printf("   Lowered statements: %zu\n", ctx->stmt_count);
    for (size_t i = 0; i < ctx->stmt_count; i++) {
        printf("     ");
        nova_expr_print(ctx->lowered_stmts[i]);
        printf("\n");
    }

    printf("   Final result: ");
    nova_expr_print(lowered);
    printf("\n");

    // Test type checking
    printf("3. Testing error propagation type checking...\n");

    nova_typecheck_context_t* tc_ctx = nova_typecheck_context_create();

    // Simulate function returning Result<i32, String>
    nova_type_t* func_return = malloc(sizeof(nova_type_t));
    func_return->kind = TYPE_RESULT;
    func_return->data.result.ok_type = malloc(sizeof(nova_type_t));  // i32
    func_return->data.result.ok_type->kind = TYPE_INT;
    func_return->data.result.err_type = malloc(sizeof(nova_type_t)); // String
    func_return->data.result.err_type->kind = TYPE_STRING;

    // Add to context
    tc_ctx->return_count = 1;
    tc_ctx->function_returns = malloc(sizeof(nova_type_t*));
    tc_ctx->function_returns[0] = func_return;

    // Test expression type (Result<i32, String>)
    nova_type_t* expr_type = malloc(sizeof(nova_type_t));
    expr_type->kind = TYPE_RESULT;
    expr_type->data.result.ok_type = malloc(sizeof(nova_type_t));
    expr_type->data.result.ok_type->kind = TYPE_INT;
    expr_type->data.result.err_type = malloc(sizeof(nova_type_t));
    expr_type->data.result.err_type->kind = TYPE_STRING;

    bool can_propagate = nova_can_propagate(tc_ctx, expr_type);
    printf("   Can propagate Result<i32, String> in Result<i32, String> function: %s\n",
           can_propagate ? "✓" : "✗");

    // Cleanup
    nova_lowering_context_destroy(ctx);
    nova_typecheck_context_destroy(tc_ctx);

    free(ok_result);
    free(err_result);

    printf("\n✅ Error model test completed!\n");
}

int main() {
    nova_test_error_model();
    return 0;
}
