#ifndef NOVA_LOWERING_TAGS_H
#define NOVA_LOWERING_TAGS_H

/* ASTNode definition */
#define NOVA_LOWERING_ASTNODE_VARDECL 0
#define NOVA_LOWERING_ASTNODE_ASSIGNMENT 1
#define NOVA_LOWERING_ASTNODE_RETURN 2
#define NOVA_LOWERING_ASTNODE_IF 3
#define NOVA_LOWERING_ASTNODE_WHILE 4
#define NOVA_LOWERING_ASTNODE_BLOCK 5
#define NOVA_LOWERING_ASTNODE_INTLITERAL 6
#define NOVA_LOWERING_ASTNODE_FLOATLITERAL 7
#define NOVA_LOWERING_ASTNODE_BOOLLITERAL 8
#define NOVA_LOWERING_ASTNODE_VARIABLE 9
#define NOVA_LOWERING_ASTNODE_BINARYOP 10
#define NOVA_LOWERING_ASTNODE_CALL 11

/* ASTType definition */
#define NOVA_LOWERING_ASTTYPE_INT 12
#define NOVA_LOWERING_ASTTYPE_FLOAT 13
#define NOVA_LOWERING_ASTTYPE_BOOL 14
#define NOVA_LOWERING_ASTTYPE_VOID 15

#endif

