#ifndef NOVA_PRATT_TAGS_H
#define NOVA_PRATT_TAGS_H

/* Associativity definition */
#define NOVA_PRATT_ASSOCIATIVITY_LEFT 0
#define NOVA_PRATT_ASSOCIATIVITY_RIGHT 1

/* ArithExpr definition */
#define NOVA_PRATT_ARITHEXPR_NUM 2
#define NOVA_PRATT_ARITHEXPR_VAR 3
#define NOVA_PRATT_ARITHEXPR_ADD 4
#define NOVA_PRATT_ARITHEXPR_SUB 5
#define NOVA_PRATT_ARITHEXPR_MUL 6
#define NOVA_PRATT_ARITHEXPR_DIV 7
#define NOVA_PRATT_ARITHEXPR_NEG 8

#endif

