#ifndef NOVA_VULKAN_TAGS_H
#define NOVA_VULKAN_TAGS_H

/* DeviceType definition */
#define NOVA_VULKAN_DEVICETYPE_DISCRETEGPU 0
#define NOVA_VULKAN_DEVICETYPE_INTEGRATEDGPU 1
#define NOVA_VULKAN_DEVICETYPE_VIRTUALGPU 2
#define NOVA_VULKAN_DEVICETYPE_CPU 3

#endif

