#ifndef NOVA_ALIAS_TAGS_H
#define NOVA_ALIAS_TAGS_H

/* AliasResult definition */
#define NOVA_ALIAS_ALIASRESULT_NOALIAS 0
#define NOVA_ALIAS_ALIASRESULT_MAYALIAS 1
#define NOVA_ALIAS_ALIASRESULT_MUSTALIAS 2
#define NOVA_ALIAS_ALIASRESULT_PARTIALALIAS 3

#endif

