#ifndef NOVA_IOS_TARGET_TAGS_H
#define NOVA_IOS_TARGET_TAGS_H

/* IOSDeviceFamily definition */
#define NOVA_IOS_TARGET_IOSDEVICEFAMILY_IPHONE 0
#define NOVA_IOS_TARGET_IOSDEVICEFAMILY_IPAD 1
#define NOVA_IOS_TARGET_IOSDEVICEFAMILY_UNIVERSAL 2
#define NOVA_IOS_TARGET_IOSDEVICEFAMILY_MACCATALYST 3

/* CompilationError definition */
#define NOVA_IOS_TARGET_COMPILATIONERROR_SWIFTGENERATIONERROR 4
#define NOVA_IOS_TARGET_COMPILATIONERROR_XCODEPROJECTERROR 5
#define NOVA_IOS_TARGET_COMPILATIONERROR_ASSETCOMPILATIONERROR 6

/* ProjectError definition */
#define NOVA_IOS_TARGET_PROJECTERROR_INVALIDBUNDLEID 7
#define NOVA_IOS_TARGET_PROJECTERROR_MISSINGPROVISIONINGPROFILE 8
#define NOVA_IOS_TARGET_PROJECTERROR_CODESIGNINGERROR 9

#endif

