#ifndef NOVA_ADVANCED_JIT_TAGS_H
#define NOVA_ADVANCED_JIT_TAGS_H

/* JITMode definition */
#define NOVA_ADVANCED_JIT_JITMODE_INTERPRETED 0
#define NOVA_ADVANCED_JIT_JITMODE_LAZYJIT 1
#define NOVA_ADVANCED_JIT_JITMODE_ADAPTIVEJIT 2
#define NOVA_ADVANCED_JIT_JITMODE_AOT 3

/* JITValue definition */
#define NOVA_ADVANCED_JIT_JITVALUE_INTEGER 4
#define NOVA_ADVANCED_JIT_JITVALUE_FLOAT 5
#define NOVA_ADVANCED_JIT_JITVALUE_BOOLEAN 6
#define NOVA_ADVANCED_JIT_JITVALUE_STRING 7

#endif

