#ifndef NOVA_CROSS_TAGS_H
#define NOVA_CROSS_TAGS_H

/* Arch definition */
#define NOVA_CROSS_ARCH_X86_64 0
#define NOVA_CROSS_ARCH_AARCH64 1
#define NOVA_CROSS_ARCH_ARM 2
#define NOVA_CROSS_ARCH_RISCV64 3
#define NOVA_CROSS_ARCH_WASM32 4

/* OS definition */
#define NOVA_CROSS_OS_LINUX 5
#define NOVA_CROSS_OS_WINDOWS 6
#define NOVA_CROSS_OS_MACOS 7
#define NOVA_CROSS_OS_IOS 8
#define NOVA_CROSS_OS_ANDROID 9
#define NOVA_CROSS_OS_FREEBSD 10
#define NOVA_CROSS_OS_NONE 11

/* Environment definition */
#define NOVA_CROSS_ENVIRONMENT_GNU 12
#define NOVA_CROSS_ENVIRONMENT_MSVC 13
#define NOVA_CROSS_ENVIRONMENT_MUSL 14
#define NOVA_CROSS_ENVIRONMENT_ANDROID 15
#define NOVA_CROSS_ENVIRONMENT_DARWIN 16
#define NOVA_CROSS_ENVIRONMENT_NONE 17

#endif

