#ifndef NOVA_CORE_TAGS_H
#define NOVA_CORE_TAGS_H

/* ParseResult definition */
#define NOVA_CORE_PARSERESULT_SUCCESS 0
#define NOVA_CORE_PARSERESULT_FAILURE 1

/* TokenKind definition */
#define NOVA_CORE_TOKENKIND_FN 2
#define NOVA_CORE_TOKENKIND_LET 3
#define NOVA_CORE_TOKENKIND_IF 4
#define NOVA_CORE_TOKENKIND_ELSE 5
#define NOVA_CORE_TOKENKIND_WHILE 6
#define NOVA_CORE_TOKENKIND_FOR 7
#define NOVA_CORE_TOKENKIND_MATCH 8
#define NOVA_CORE_TOKENKIND_RETURN 9
#define NOVA_CORE_TOKENKIND_PLUS 10
#define NOVA_CORE_TOKENKIND_MINUS 11
#define NOVA_CORE_TOKENKIND_STAR 12
#define NOVA_CORE_TOKENKIND_SLASH 13
#define NOVA_CORE_TOKENKIND_EQ 14
#define NOVA_CORE_TOKENKIND_EQEQ 15
#define NOVA_CORE_TOKENKIND_LT 16
#define NOVA_CORE_TOKENKIND_GT 17
#define NOVA_CORE_TOKENKIND_LPAREN 18
#define NOVA_CORE_TOKENKIND_RPAREN 19
#define NOVA_CORE_TOKENKIND_LBRACE 20
#define NOVA_CORE_TOKENKIND_RBRACE 21
#define NOVA_CORE_TOKENKIND_LBRACKET 22
#define NOVA_CORE_TOKENKIND_RBRACKET 23
#define NOVA_CORE_TOKENKIND_COMMA 24
#define NOVA_CORE_TOKENKIND_SEMICOLON 25
#define NOVA_CORE_TOKENKIND_COLON 26
#define NOVA_CORE_TOKENKIND_ARROW 27
#define NOVA_CORE_TOKENKIND_INTLIT 28
#define NOVA_CORE_TOKENKIND_STRINGLIT 29
#define NOVA_CORE_TOKENKIND_BOOLLIT 30
#define NOVA_CORE_TOKENKIND_IDENT 31
#define NOVA_CORE_TOKENKIND_EOF 32

#endif

