#ifndef NOVA_MULTILINGUAL_TAGS_H
#define NOVA_MULTILINGUAL_TAGS_H

/* TargetPlatform definition */
#define NOVA_MULTILINGUAL_TARGETPLATFORM_CPU 0
#define NOVA_MULTILINGUAL_TARGETPLATFORM_GPU 1
#define NOVA_MULTILINGUAL_TARGETPLATFORM_TPU 2
#define NOVA_MULTILINGUAL_TARGETPLATFORM_NPU 3
#define NOVA_MULTILINGUAL_TARGETPLATFORM_UNIFIED 4

/* GPUVendor definition */
#define NOVA_MULTILINGUAL_GPUVENDOR_NVIDIA 5
#define NOVA_MULTILINGUAL_GPUVENDOR_AMD 6
#define NOVA_MULTILINGUAL_GPUVENDOR_INTEL 7
#define NOVA_MULTILINGUAL_GPUVENDOR_APPLE 8

/* MultilingualError definition */
#define NOVA_MULTILINGUAL_MULTILINGUALERROR_UNSUPPORTEDLANGUAGE 9
#define NOVA_MULTILINGUAL_MULTILINGUALERROR_TRANSLATIONERROR 10
#define NOVA_MULTILINGUAL_MULTILINGUALERROR_CULTURALADAPTATIONERROR 11
#define NOVA_MULTILINGUAL_MULTILINGUALERROR_COMPILATIONERROR 12
#define NOVA_MULTILINGUAL_MULTILINGUALERROR_FALLBACKERROR 13

#endif

