#ifndef NOVA_TRANSFORM_TAGS_H
#define NOVA_TRANSFORM_TAGS_H

/* MIRPass definition */
#define NOVA_TRANSFORM_MIRPASS_CONSTPROP 0
#define NOVA_TRANSFORM_MIRPASS_DEADCODEELIM 1
#define NOVA_TRANSFORM_MIRPASS_HARMONICUNROLL 2
#define NOVA_TRANSFORM_MIRPASS_SIMDVECTORIZE 3
#define NOVA_TRANSFORM_MIRPASS_INLINING 4

#endif

