#ifndef NOVA_AST_TO_MLIR_TAGS_H
#define NOVA_AST_TO_MLIR_TAGS_H

/* MLIRType definition */
#define NOVA_AST_TO_MLIR_MLIRTYPE_I64 0
#define NOVA_AST_TO_MLIR_MLIRTYPE_F64 1
#define NOVA_AST_TO_MLIR_MLIRTYPE_BOOL 2
#define NOVA_AST_TO_MLIR_MLIRTYPE_LINEAR 3
#define NOVA_AST_TO_MLIR_MLIRTYPE_BORROWED 4
#define NOVA_AST_TO_MLIR_MLIRTYPE_OWNED 5

/* MLIROperation definition */
#define NOVA_AST_TO_MLIR_MLIROPERATION_MOVE 6
#define NOVA_AST_TO_MLIR_MLIROPERATION_BORROW 7
#define NOVA_AST_TO_MLIR_MLIROPERATION_DROP 8
#define NOVA_AST_TO_MLIR_MLIROPERATION_CALL 9
#define NOVA_AST_TO_MLIR_MLIROPERATION_PURECALL 10
#define NOVA_AST_TO_MLIR_MLIROPERATION_WITHEFFECT 11
#define NOVA_AST_TO_MLIR_MLIROPERATION_VERIFY 12
#define NOVA_AST_TO_MLIR_MLIROPERATION_VERIFIEDBLOCK 13

/* EffectSet definition */
#define NOVA_AST_TO_MLIR_EFFECTSET_PURE 14
#define NOVA_AST_TO_MLIR_EFFECTSET_IO 15
#define NOVA_AST_TO_MLIR_EFFECTSET_MEMORY 16
#define NOVA_AST_TO_MLIR_EFFECTSET_UNKNOWN 17

#endif

