#ifndef NOVA_WINDOW_SYSTEM_TAGS_H
#define NOVA_WINDOW_SYSTEM_TAGS_H

/* CursorType definition */
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_ARROW 0
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_IBEAM 1
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_CROSSHAIR 2
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_HAND 3
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_HRESIZE 4
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_VRESIZE 5
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_NWRESIZE 6
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_NERESIZE 7
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_SWRESIZE 8
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_SERESIZE 9
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_WAIT 10
#define NOVA_WINDOW_SYSTEM_CURSORTYPE_NONE 11

/* EventType definition */
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_WINDOWCLOSE 12
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_WINDOWRESIZE 13
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_WINDOWMOVE 14
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_WINDOWFOCUS 15
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_WINDOWBLUR 16
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_KEYPRESS 17
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_KEYRELEASE 18
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_MOUSEMOVE 19
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_MOUSEBUTTONPRESS 20
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_MOUSEBUTTONRELEASE 21
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_MOUSESCROLL 22
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_TEXTINPUT 23
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_FILEDROP 24
#define NOVA_WINDOW_SYSTEM_EVENTTYPE_CUSTOM 25

/* EventData definition */
#define NOVA_WINDOW_SYSTEM_EVENTDATA_WINDOWEVENT 26
#define NOVA_WINDOW_SYSTEM_EVENTDATA_KEYBOARDEVENT 27
#define NOVA_WINDOW_SYSTEM_EVENTDATA_MOUSEEVENT 28
#define NOVA_WINDOW_SYSTEM_EVENTDATA_TEXTEVENT 29
#define NOVA_WINDOW_SYSTEM_EVENTDATA_FILEDROPEVENT 30
#define NOVA_WINDOW_SYSTEM_EVENTDATA_CUSTOMEVENT 31

/* WindowEventType definition */
#define NOVA_WINDOW_SYSTEM_WINDOWEVENTTYPE_CLOSED 32
#define NOVA_WINDOW_SYSTEM_WINDOWEVENTTYPE_RESIZED 33
#define NOVA_WINDOW_SYSTEM_WINDOWEVENTTYPE_MOVED 34
#define NOVA_WINDOW_SYSTEM_WINDOWEVENTTYPE_FOCUSED 35
#define NOVA_WINDOW_SYSTEM_WINDOWEVENTTYPE_BLURRED 36
#define NOVA_WINDOW_SYSTEM_WINDOWEVENTTYPE_MINIMIZED 37
#define NOVA_WINDOW_SYSTEM_WINDOWEVENTTYPE_MAXIMIZED 38
#define NOVA_WINDOW_SYSTEM_WINDOWEVENTTYPE_RESTORED 39

/* Key definition */
#define NOVA_WINDOW_SYSTEM_KEY_A 40
#define NOVA_WINDOW_SYSTEM_KEY_B 41
#define NOVA_WINDOW_SYSTEM_KEY_C 42
#define NOVA_WINDOW_SYSTEM_KEY_D 43
#define NOVA_WINDOW_SYSTEM_KEY_E 44
#define NOVA_WINDOW_SYSTEM_KEY_F 45
#define NOVA_WINDOW_SYSTEM_KEY_G 46
#define NOVA_WINDOW_SYSTEM_KEY_H 47
#define NOVA_WINDOW_SYSTEM_KEY_I 48
#define NOVA_WINDOW_SYSTEM_KEY_J 49
#define NOVA_WINDOW_SYSTEM_KEY_K 50
#define NOVA_WINDOW_SYSTEM_KEY_L 51
#define NOVA_WINDOW_SYSTEM_KEY_M 52
#define NOVA_WINDOW_SYSTEM_KEY_N 53
#define NOVA_WINDOW_SYSTEM_KEY_O 54
#define NOVA_WINDOW_SYSTEM_KEY_P 55
#define NOVA_WINDOW_SYSTEM_KEY_Q 56
#define NOVA_WINDOW_SYSTEM_KEY_R 57
#define NOVA_WINDOW_SYSTEM_KEY_S 58
#define NOVA_WINDOW_SYSTEM_KEY_T 59
#define NOVA_WINDOW_SYSTEM_KEY_U 60
#define NOVA_WINDOW_SYSTEM_KEY_V 61
#define NOVA_WINDOW_SYSTEM_KEY_W 62
#define NOVA_WINDOW_SYSTEM_KEY_X 63
#define NOVA_WINDOW_SYSTEM_KEY_Y 64
#define NOVA_WINDOW_SYSTEM_KEY_Z 65
#define NOVA_WINDOW_SYSTEM_KEY_NUM0 66
#define NOVA_WINDOW_SYSTEM_KEY_NUM1 67
#define NOVA_WINDOW_SYSTEM_KEY_NUM2 68
#define NOVA_WINDOW_SYSTEM_KEY_NUM3 69
#define NOVA_WINDOW_SYSTEM_KEY_NUM4 70
#define NOVA_WINDOW_SYSTEM_KEY_NUM5 71
#define NOVA_WINDOW_SYSTEM_KEY_NUM6 72
#define NOVA_WINDOW_SYSTEM_KEY_NUM7 73
#define NOVA_WINDOW_SYSTEM_KEY_NUM8 74
#define NOVA_WINDOW_SYSTEM_KEY_NUM9 75
#define NOVA_WINDOW_SYSTEM_KEY_ESCAPE 76
#define NOVA_WINDOW_SYSTEM_KEY_F1 77
#define NOVA_WINDOW_SYSTEM_KEY_F2 78
#define NOVA_WINDOW_SYSTEM_KEY_F3 79
#define NOVA_WINDOW_SYSTEM_KEY_F4 80
#define NOVA_WINDOW_SYSTEM_KEY_F5 81
#define NOVA_WINDOW_SYSTEM_KEY_F6 82
#define NOVA_WINDOW_SYSTEM_KEY_F7 83
#define NOVA_WINDOW_SYSTEM_KEY_F8 84
#define NOVA_WINDOW_SYSTEM_KEY_F9 85
#define NOVA_WINDOW_SYSTEM_KEY_F10 86
#define NOVA_WINDOW_SYSTEM_KEY_F11 87
#define NOVA_WINDOW_SYSTEM_KEY_F12 88
#define NOVA_WINDOW_SYSTEM_KEY_PRINTSCREEN 89
#define NOVA_WINDOW_SYSTEM_KEY_SCROLLLOCK 90
#define NOVA_WINDOW_SYSTEM_KEY_PAUSE 91
#define NOVA_WINDOW_SYSTEM_KEY_INSERT 92
#define NOVA_WINDOW_SYSTEM_KEY_DELETE 93
#define NOVA_WINDOW_SYSTEM_KEY_HOME 94
#define NOVA_WINDOW_SYSTEM_KEY_END 95
#define NOVA_WINDOW_SYSTEM_KEY_PAGEUP 96
#define NOVA_WINDOW_SYSTEM_KEY_PAGEDOWN 97
#define NOVA_WINDOW_SYSTEM_KEY_LEFT 98
#define NOVA_WINDOW_SYSTEM_KEY_RIGHT 99
#define NOVA_WINDOW_SYSTEM_KEY_UP 100
#define NOVA_WINDOW_SYSTEM_KEY_DOWN 101
#define NOVA_WINDOW_SYSTEM_KEY_BACKSPACE 102
#define NOVA_WINDOW_SYSTEM_KEY_TAB 103
#define NOVA_WINDOW_SYSTEM_KEY_RETURN 104
#define NOVA_WINDOW_SYSTEM_KEY_SPACE 105
#define NOVA_WINDOW_SYSTEM_KEY_LSHIFT 106
#define NOVA_WINDOW_SYSTEM_KEY_RSHIFT 107
#define NOVA_WINDOW_SYSTEM_KEY_LCTRL 108
#define NOVA_WINDOW_SYSTEM_KEY_RCTRL 109
#define NOVA_WINDOW_SYSTEM_KEY_LALT 110
#define NOVA_WINDOW_SYSTEM_KEY_RALT 111
#define NOVA_WINDOW_SYSTEM_KEY_LSUPER 112
#define NOVA_WINDOW_SYSTEM_KEY_RSUPER 113
#define NOVA_WINDOW_SYSTEM_KEY_MENU 114
#define NOVA_WINDOW_SYSTEM_KEY_CAPSLOCK 115
#define NOVA_WINDOW_SYSTEM_KEY_NUMLOCK 116

/* MouseButton definition */
#define NOVA_WINDOW_SYSTEM_MOUSEBUTTON_LEFT 117
#define NOVA_WINDOW_SYSTEM_MOUSEBUTTON_RIGHT 118
#define NOVA_WINDOW_SYSTEM_MOUSEBUTTON_MIDDLE 119
#define NOVA_WINDOW_SYSTEM_MOUSEBUTTON_X1 120
#define NOVA_WINDOW_SYSTEM_MOUSEBUTTON_X2 121

/* EventResult definition */
#define NOVA_WINDOW_SYSTEM_EVENTRESULT_CONTINUE 122
#define NOVA_WINDOW_SYSTEM_EVENTRESULT_HANDLED 123
#define NOVA_WINDOW_SYSTEM_EVENTRESULT_STOPPROPAGATION 124

/* WindowError definition */
#define NOVA_WINDOW_SYSTEM_WINDOWERROR_CREATIONFAILED 125
#define NOVA_WINDOW_SYSTEM_WINDOWERROR_INVALIDCONFIG 126
#define NOVA_WINDOW_SYSTEM_WINDOWERROR_PLATFORMERROR 127

/* AppError definition */
#define NOVA_WINDOW_SYSTEM_APPERROR_INITIALIZATIONFAILED 128
#define NOVA_WINDOW_SYSTEM_APPERROR_WINDOWCREATIONFAILED 129
#define NOVA_WINDOW_SYSTEM_APPERROR_EVENTLOOPERROR 130

#endif

