#ifndef NOVA_DOM_BINDINGS_TAGS_H
#define NOVA_DOM_BINDINGS_TAGS_H

/* Node definition */
#define NOVA_DOM_BINDINGS_NODE_ELEMENT 0
#define NOVA_DOM_BINDINGS_NODE_TEXT 1
#define NOVA_DOM_BINDINGS_NODE_COMMENT 2

/* EventType definition */
#define NOVA_DOM_BINDINGS_EVENTTYPE_CLICK 3
#define NOVA_DOM_BINDINGS_EVENTTYPE_DOUBLECLICK 4
#define NOVA_DOM_BINDINGS_EVENTTYPE_MOUSEDOWN 5
#define NOVA_DOM_BINDINGS_EVENTTYPE_MOUSEUP 6
#define NOVA_DOM_BINDINGS_EVENTTYPE_MOUSEMOVE 7
#define NOVA_DOM_BINDINGS_EVENTTYPE_MOUSEENTER 8
#define NOVA_DOM_BINDINGS_EVENTTYPE_MOUSELEAVE 9
#define NOVA_DOM_BINDINGS_EVENTTYPE_KEYDOWN 10
#define NOVA_DOM_BINDINGS_EVENTTYPE_KEYUP 11
#define NOVA_DOM_BINDINGS_EVENTTYPE_KEYPRESS 12
#define NOVA_DOM_BINDINGS_EVENTTYPE_FOCUS 13
#define NOVA_DOM_BINDINGS_EVENTTYPE_BLUR 14
#define NOVA_DOM_BINDINGS_EVENTTYPE_CHANGE 15
#define NOVA_DOM_BINDINGS_EVENTTYPE_INPUT 16
#define NOVA_DOM_BINDINGS_EVENTTYPE_SUBMIT 17
#define NOVA_DOM_BINDINGS_EVENTTYPE_LOAD 18
#define NOVA_DOM_BINDINGS_EVENTTYPE_UNLOAD 19
#define NOVA_DOM_BINDINGS_EVENTTYPE_RESIZE 20
#define NOVA_DOM_BINDINGS_EVENTTYPE_SCROLL 21
#define NOVA_DOM_BINDINGS_EVENTTYPE_CUSTOM 22

/* EventResult definition */
#define NOVA_DOM_BINDINGS_EVENTRESULT_CONTINUE 23
#define NOVA_DOM_BINDINGS_EVENTRESULT_STOPPROPAGATION 24
#define NOVA_DOM_BINDINGS_EVENTRESULT_PREVENTDEFAULT 25
#define NOVA_DOM_BINDINGS_EVENTRESULT_BOTH 26

/* WebSocketState definition */
#define NOVA_DOM_BINDINGS_WEBSOCKETSTATE_CONNECTING 27
#define NOVA_DOM_BINDINGS_WEBSOCKETSTATE_OPEN 28
#define NOVA_DOM_BINDINGS_WEBSOCKETSTATE_CLOSING 29
#define NOVA_DOM_BINDINGS_WEBSOCKETSTATE_CLOSED 30

/* WebSocketEventType definition */
#define NOVA_DOM_BINDINGS_WEBSOCKETEVENTTYPE_OPEN 31
#define NOVA_DOM_BINDINGS_WEBSOCKETEVENTTYPE_MESSAGE 32
#define NOVA_DOM_BINDINGS_WEBSOCKETEVENTTYPE_ERROR 33
#define NOVA_DOM_BINDINGS_WEBSOCKETEVENTTYPE_CLOSE 34

/* HttpMethod definition */
#define NOVA_DOM_BINDINGS_HTTPMETHOD_GET 35
#define NOVA_DOM_BINDINGS_HTTPMETHOD_POST 36
#define NOVA_DOM_BINDINGS_HTTPMETHOD_PUT 37
#define NOVA_DOM_BINDINGS_HTTPMETHOD_DELETE 38
#define NOVA_DOM_BINDINGS_HTTPMETHOD_PATCH 39
#define NOVA_DOM_BINDINGS_HTTPMETHOD_HEAD 40
#define NOVA_DOM_BINDINGS_HTTPMETHOD_OPTIONS 41

/* ResponseType definition */
#define NOVA_DOM_BINDINGS_RESPONSETYPE_TEXT 42
#define NOVA_DOM_BINDINGS_RESPONSETYPE_JSON 43
#define NOVA_DOM_BINDINGS_RESPONSETYPE_ARRAYBUFFER 44
#define NOVA_DOM_BINDINGS_RESPONSETYPE_BLOB 45

/* DOMError definition */
#define NOVA_DOM_BINDINGS_DOMERROR_ELEMENTNOTFOUND 46
#define NOVA_DOM_BINDINGS_DOMERROR_INVALIDSELECTOR 47
#define NOVA_DOM_BINDINGS_DOMERROR_NOTFOUND 48
#define NOVA_DOM_BINDINGS_DOMERROR_HIERARCHYERROR 49

/* HttpError definition */
#define NOVA_DOM_BINDINGS_HTTPERROR_NETWORKERROR 50
#define NOVA_DOM_BINDINGS_HTTPERROR_TIMEOUT 51
#define NOVA_DOM_BINDINGS_HTTPERROR_PARSEERROR 52
#define NOVA_DOM_BINDINGS_HTTPERROR_STATUSERROR 53

/* GeolocationError definition */
#define NOVA_DOM_BINDINGS_GEOLOCATIONERROR_PERMISSIONDENIED 54
#define NOVA_DOM_BINDINGS_GEOLOCATIONERROR_POSITIONUNAVAILABLE 55
#define NOVA_DOM_BINDINGS_GEOLOCATIONERROR_TIMEOUT 56

/* NotificationError definition */
#define NOVA_DOM_BINDINGS_NOTIFICATIONERROR_PERMISSIONDENIED 57
#define NOVA_DOM_BINDINGS_NOTIFICATIONERROR_NOTSUPPORTED 58
#define NOVA_DOM_BINDINGS_NOTIFICATIONERROR_INVALIDOPTIONS 59

/* NotificationPermission definition */
#define NOVA_DOM_BINDINGS_NOTIFICATIONPERMISSION_GRANTED 60
#define NOVA_DOM_BINDINGS_NOTIFICATIONPERMISSION_DENIED 61
#define NOVA_DOM_BINDINGS_NOTIFICATIONPERMISSION_DEFAULT 62

#endif

