#ifndef NOVA_ERRORS_TAGS_H
#define NOVA_ERRORS_TAGS_H

/* CompilerError definition */
#define NOVA_ERRORS_COMPILERERROR_LEXICAL 0
#define NOVA_ERRORS_COMPILERERROR_SYNTAX 1
#define NOVA_ERRORS_COMPILERERROR_SEMANTIC 2
#define NOVA_ERRORS_COMPILERERROR_TYPE 3
#define NOVA_ERRORS_COMPILERERROR_SYMBOL 4
#define NOVA_ERRORS_COMPILERERROR_CODEGEN 5
#define NOVA_ERRORS_COMPILERERROR_RUNTIME 6

/* SemanticErrorKind definition */
#define NOVA_ERRORS_SEMANTICERRORKIND_UNREACHABLECODE 7
#define NOVA_ERRORS_SEMANTICERRORKIND_UNUSEDVARIABLE 8
#define NOVA_ERRORS_SEMANTICERRORKIND_UNUSEDFUNCTION 9
#define NOVA_ERRORS_SEMANTICERRORKIND_MISSINGRETURN 10
#define NOVA_ERRORS_SEMANTICERRORKIND_DEADCODE 11
#define NOVA_ERRORS_SEMANTICERRORKIND_INFINITELOOP 12
#define NOVA_ERRORS_SEMANTICERRORKIND_CONTRACTVIOLATION 13
#define NOVA_ERRORS_SEMANTICERRORKIND_UNSAFEOPERATION 14
#define NOVA_ERRORS_SEMANTICERRORKIND_DEPRECATEDUSAGE 15

/* SymbolKind definition */
#define NOVA_ERRORS_SYMBOLKIND_VARIABLE 16
#define NOVA_ERRORS_SYMBOLKIND_FUNCTION 17
#define NOVA_ERRORS_SYMBOLKIND_DATATYPE 18
#define NOVA_ERRORS_SYMBOLKIND_TRAIT 19
#define NOVA_ERRORS_SYMBOLKIND_MODULE 20
#define NOVA_ERRORS_SYMBOLKIND_FIELD 21
#define NOVA_ERRORS_SYMBOLKIND_METHOD 22
#define NOVA_ERRORS_SYMBOLKIND_CONSTANT 23
#define NOVA_ERRORS_SYMBOLKIND_TYPEALIAS 24
#define NOVA_ERRORS_SYMBOLKIND_MACRO 25

/* SymbolError definition */
#define NOVA_ERRORS_SYMBOLERROR_NOTFOUND 26
#define NOVA_ERRORS_SYMBOLERROR_ALREADYDEFINED 27
#define NOVA_ERRORS_SYMBOLERROR_WRONGKIND 28
#define NOVA_ERRORS_SYMBOLERROR_NOTACCESSIBLE 29
#define NOVA_ERRORS_SYMBOLERROR_CIRCULARREFERENCE 30

/* CodeGenPhase definition */
#define NOVA_ERRORS_CODEGENPHASE_IRGENERATION 31
#define NOVA_ERRORS_CODEGENPHASE_OPTIMIZATION 32
#define NOVA_ERRORS_CODEGENPHASE_TARGETCODEEMISSION 33
#define NOVA_ERRORS_CODEGENPHASE_LINKING 34

/* Severity definition */
#define NOVA_ERRORS_SEVERITY_ERROR 35
#define NOVA_ERRORS_SEVERITY_WARNING 36
#define NOVA_ERRORS_SEVERITY_INFO 37
#define NOVA_ERRORS_SEVERITY_HINT 38

#endif

