#ifndef NOVA_DATAFLOW_TAGS_H
#define NOVA_DATAFLOW_TAGS_H

/* DataflowDirection definition */
#define NOVA_DATAFLOW_DATAFLOWDIRECTION_FORWARD 0
#define NOVA_DATAFLOW_DATAFLOWDIRECTION_BACKWARD 1

#endif

