#ifndef NOVA_LLVM_BACKEND_TAGS_H
#define NOVA_LLVM_BACKEND_TAGS_H

/* BackendError definition */
#define NOVA_LLVM_BACKEND_BACKENDERROR_UNSUPPORTEDFEATURE 0
#define NOVA_LLVM_BACKEND_BACKENDERROR_TYPEMISMATCH 1
#define NOVA_LLVM_BACKEND_BACKENDERROR_UNDEFINEDSYMBOL 2
#define NOVA_LLVM_BACKEND_BACKENDERROR_INTERNALERROR 3

#endif

